// Tier Q7 — API contract testing.
//
// Full response-shape snapshot fixtures from every route is a multi-day
// effort (requires a test backend with seeded data + 200+ route calls).
// This file ships the pragmatic Q7 ratchet:
//
//   1. Export-shape snapshot per domain api object — `recipeApi`,
//      `mealApi`, `foodApi`, etc. expose a deterministic set of function
//      names. If a refactor renames or removes one, the snapshot fails
//      and the PR author must explicitly update both the api AND every
//      caller.
//   2. Typed-response coverage floor per domain — at least one
//      `apiClient.<verb><TResponse>(...)` form per domain file. Tracks
//      the percentage of typed responses over time. Growth in untyped
//      writes is allowed (incremental migration) but a domain dropping
//      to 0 typed responses fails the test.
//   3. Banned response-shape patterns — no domain api should declare a
//      response with `any` in the inferred return position. Catches
//      `apiClient.post('...')` where TS can't surface drift.

import * as fs from 'fs';
import * as path from 'path';

const FRONTEND_ROOT = path.resolve(__dirname, '../..');
const API_ROOT = path.join(FRONTEND_ROOT, 'lib', 'api');

const DOMAIN_FILES = [
  'coach.ts',
  'food.ts',
  'meal.ts',
  'plate.ts',
  'recipe.ts',
  'search.ts',
  'shopping.ts',
  'today.ts',
  'user.ts',
] as const;

interface DomainSnapshot {
  file: string;
  exportedFns: string[];
  totalCallsites: number;
  typedCallsites: number;
}

const VERB_PATTERN = /apiClient\.(?:post|put|patch|delete|get)\(/g;
const TYPED_VERB_PATTERN = /apiClient\.(?:post|put|patch|delete|get)<[A-Z]/g;

function snapshotDomain(file: string): DomainSnapshot {
  const src = fs.readFileSync(path.join(API_ROOT, file), 'utf-8');

  // Extract function-style export names inside the top-level api object.
  // We pin the inner fn names; the object name itself can be renamed only
  // by also updating callers (which would surface in tsc).
  // Match `funcName: ... =>` or `funcName(args) {`
  const fnRe = /^\s*(?:async\s+)?([a-z][A-Za-z0-9]*)\s*(?:\([^)]*\)\s*[:=]|:\s*(?:async\s*)?\([^)]*\)\s*=>)/gm;
  const exported = new Set<string>();
  let m: RegExpExecArray | null;
  while ((m = fnRe.exec(src)) !== null) {
    exported.add(m[1]);
  }

  // Total api-verb callsites
  const total = (src.match(VERB_PATTERN) || []).length;
  const typed = (src.match(TYPED_VERB_PATTERN) || []).length;

  return {
    file,
    exportedFns: [...exported].sort(),
    totalCallsites: total,
    typedCallsites: typed,
  };
}

// ─── Snapshot baselines (recorded 2026-05-10) ───────────────────────────
// Each domain's snapshot fn count is pinned. If a function is renamed or
// removed without a coordinated PR, the count changes and this test fails.
// If a function is ADDED, the snapshot file is regenerated by hand
// (intentional growth is fine; surprise shrinkage is not).
const DOMAIN_FN_COUNT_FLOOR: Record<string, number> = {
  'coach.ts': 5,
  'food.ts': 5,
  'meal.ts': 5,
  'plate.ts': 3,
  'recipe.ts': 10,
  'search.ts': 2,
  'shopping.ts': 5,
  'today.ts': 3,
  'user.ts': 5,
};

describe('Q7 — API contract', () => {
  describe('domain api files exist', () => {
    for (const f of DOMAIN_FILES) {
      it(`${f} exists`, () => {
        expect(fs.existsSync(path.join(API_ROOT, f))).toBe(true);
      });
    }
  });

  describe('export shape per domain', () => {
    for (const f of DOMAIN_FILES) {
      it(`${f}: function-count ≥ ${DOMAIN_FN_COUNT_FLOOR[f]}`, () => {
        const snap = snapshotDomain(f);
        if (snap.exportedFns.length < DOMAIN_FN_COUNT_FLOOR[f]) {
          throw new Error(
            `${f}: exported function count dropped from baseline ${DOMAIN_FN_COUNT_FLOOR[f]} to ${snap.exportedFns.length}. ` +
              `Functions present: ${snap.exportedFns.join(', ')}. ` +
              `If this is intentional, update DOMAIN_FN_COUNT_FLOOR.`,
          );
        }
        expect(snap.exportedFns.length).toBeGreaterThanOrEqual(DOMAIN_FN_COUNT_FLOOR[f]);
      });
    }
  });

  describe('typed-response coverage (per-domain floor)', () => {
    // Some domains already have typed responses; some haven't migrated yet.
    // Floor: each domain that HAS typed responses today must keep at least
    // one (drift detector). Migration to fuller typing is recommended but
    // not enforced at the file level here.
    const HAS_TYPED_TODAY = ['food.ts', 'today.ts'];

    for (const f of HAS_TYPED_TODAY) {
      it(`${f}: keeps at least one typed apiClient.<verb><TResponse>(...) form`, () => {
        const snap = snapshotDomain(f);
        expect(snap.typedCallsites).toBeGreaterThan(0);
      });
    }
  });

  describe('total callsite floor (drift detector)', () => {
    it('aggregate write+read callsite count across all domains ≥ 200', () => {
      let total = 0;
      for (const f of DOMAIN_FILES) {
        total += snapshotDomain(f).totalCallsites;
      }
      // Today's baseline: ~210 api calls across the 10 domains. Floor
      // 200 catches accidental mass-deletion.
      expect(total).toBeGreaterThanOrEqual(200);
    });
  });

  describe('banned-pattern guards', () => {
    it('no domain file uses `any` as an explicit response generic', () => {
      // Catches the anti-pattern: `apiClient.post<any>(...)` — explicitly
      // typed as `any` is worse than untyped, because it lies about the
      // contract being checked.
      const offenders: string[] = [];
      for (const f of DOMAIN_FILES) {
        const src = fs.readFileSync(path.join(API_ROOT, f), 'utf-8');
        if (/apiClient\.(?:post|put|patch|delete|get)<any\b/.test(src)) {
          offenders.push(f);
        }
      }
      expect(offenders).toEqual([]);
    });

    it('no domain file imports `unknown` and immediately casts it', () => {
      // `... as Response` after `apiClient.get<unknown>(...)` is also a
      // contract bypass. Surface any occurrences.
      const offenders: string[] = [];
      for (const f of DOMAIN_FILES) {
        const src = fs.readFileSync(path.join(API_ROOT, f), 'utf-8');
        if (/apiClient\.(?:post|put|patch|delete|get)<unknown>[\s\S]{0,80}as\s+\w/.test(src)) {
          offenders.push(f);
        }
      }
      expect(offenders).toEqual([]);
    });
  });
});
