// frontend/constants/colorTokens.cjs
//
// Single source of truth for color tokens. Consumed by:
//   - constants/tokens.ts        (RN-typed re-exports + helpers)
//   - tailwind.config.js          (NativeWind colors object)
//   - global.css                  (CSS :root vars — generated by buildTokens)
//
// CommonJS so tailwind.config.js can require() it without a TS loader.
// See frontend/design.md for philosophy.

const Canvas = {
  light: '#FFFFFF',
  dark: '#0A0A0A',
  warmLight: '#FAF7F4',
  warmDark: '#1A1410',
};

const Surface = {
  light: { base: '#FFFFFF', raised: '#FFFFFF', overlay: '#FFFFFF', tint: '#F8F8F8' },
  dark: { base: '#141414', raised: '#1F1F1F', overlay: '#2A2A2A', tint: '#1A1A1A' },
};

const Brand = {
  light: { base: '#fa7e12', deep: '#d67a0c', soft: '#FFF0E5', ink: '#FFFFFF' },
  dark: { base: '#FF9559', deep: '#E07A40', soft: 'rgba(255,149,89,0.14)', ink: '#1A1410' },
};

const PastelTokens = {
  light: {
    sage: '#E8F5E9',
    golden: '#FFF8E1',
    lavender: '#F3E5F5',
    peach: '#FFF3E0',
    sky: '#E3F2FD',
    blush: '#FCE4EC',
    orange: '#FFF0E5',
    red: '#FFF0EE',
  },
  dark: {
    sage: 'rgba(129,199,132,0.12)',
    golden: 'rgba(255,213,79,0.12)',
    lavender: 'rgba(206,147,216,0.12)',
    peach: 'rgba(255,183,77,0.12)',
    sky: 'rgba(100,181,246,0.12)',
    blush: 'rgba(240,98,146,0.12)',
    orange: 'rgba(255,139,65,0.12)',
    red: 'rgba(239,68,68,0.12)',
  },
};

const AccentTokens = {
  sage: '#81C784',
  golden: '#FFD54F',
  lavender: '#CE93D8',
  peach: '#FFB74D',
  sky: '#64B5F6',
  blush: '#F06292',
};

const Ink = {
  light: { primary: '#0A0A0A', secondary: '#525252', tertiary: '#8A8A8A', inverse: '#FFFFFF', warm: '#1d1d1f' },
  dark: { primary: '#F5F5F5', secondary: '#A8A8A8', tertiary: '#6B6B6B', inverse: '#0A0A0A', warm: '#F5EFE6' },
};

const Hairline = {
  light: { hairline: 'rgba(10,10,10,0.06)', soft: 'rgba(10,10,10,0.10)', strong: 'rgba(10,10,10,0.18)' },
  dark: { hairline: 'rgba(255,255,255,0.08)', soft: 'rgba(255,255,255,0.14)', strong: 'rgba(255,255,255,0.24)' },
};

const Semantic = {
  light: { success: '#10B981', warning: '#F59E0B', error: '#EF4444', info: '#3B82F6' },
  dark: { success: '#34D399', warning: '#FBBF24', error: '#F87171', info: '#60A5FA' },
};

const Backdrop = {
  light: 'rgba(0,0,0,0.4)',
  heavy: 'rgba(0,0,0,0.7)',
  lightDark: 'rgba(0,0,0,0.6)',
  heavyDark: 'rgba(0,0,0,0.85)',
};

const PeakShadow = {
  lightColor: '#d67a0c',
  darkColor: '#E07A40',
  depth: 4,
  pressTranslate: 4,
};

module.exports = {
  Canvas,
  Surface,
  Brand,
  PastelTokens,
  AccentTokens,
  Ink,
  Hairline,
  Semantic,
  Backdrop,
  PeakShadow,
};
