// frontend/constants/colorTokens.cjs
//
// Single source of truth for color tokens. Consumed by:
//   - constants/tokens.ts        (RN-typed re-exports + helpers)
//   - tailwind.config.js          (NativeWind colors object)
//   - global.css                  (CSS :root vars — generated by buildTokens)
//
// CommonJS so tailwind.config.js can require() it without a TS loader.
// See frontend/design.md for philosophy.

const Canvas = {
  light: '#FFFFFF',
  dark: '#0A0A0A',
  warmLight: '#FAF7F4',
  warmDark: '#1A1410',
};

const Surface = {
  light: { base: '#FFFFFF', raised: '#FFFFFF', overlay: '#FFFFFF', tint: '#F8F8F8' },
  dark: { base: '#141414', raised: '#1F1F1F', overlay: '#2A2A2A', tint: '#1A1A1A' },
};

const Brand = {
  light: { base: '#fa7e12', deep: '#d67a0c', soft: '#FFF0E5', ink: '#FFFFFF' },
  dark: { base: '#FF9559', deep: '#E07A40', soft: 'rgba(255,149,89,0.14)', ink: '#1A1410' },
};

const PastelTokens = {
  light: {
    sage: '#E8F5E9',
    golden: '#FFF8E1',
    lavender: '#F3E5F5',
    peach: '#FFF3E0',
    sky: '#E3F2FD',
    blush: '#FCE4EC',
    orange: '#FFF0E5',
    red: '#FFF0EE',
  },
  // DS2.1 — solid muted-jewel wins over 12% rgba.
  // Each value is the rgba-over-#141414 composite of the previous version, so
  // visual rendering on the default dark surface is byte-identical, but the
  // token no longer depends on transparency stacking (which goes muddy on
  // surface-raised / cards-on-cards). See docs/design-decisions/DS2.1.md.
  dark: {
    sage: '#212921',
    golden: '#302B1B',
    lavender: '#2A232C',
    peach: '#30281B',
    sky: '#1E272F',
    blush: '#2E1D23',
    orange: '#302219',
    red: '#2E1A1A',
  },
};

const AccentTokens = {
  sage: '#81C784',
  golden: '#FFD54F',
  lavender: '#CE93D8',
  peach: '#FFB74D',
  sky: '#64B5F6',
  blush: '#F06292',
};

const Ink = {
  // tertiary darkened (light) / lightened (dark) on 2026-05-14 so body text
  // at tertiary tier clears WCAG AA 4.5:1 on canvas + canvas-warm. Prior
  // values (#8A8A8A / #6B6B6B) scored ~3.5:1 and were a documented "large
  // text only" hazard; failing rows in docs/CONTRAST.md drove the call.
  light: { primary: '#0A0A0A', secondary: '#525252', tertiary: '#6B6B6B', inverse: '#FFFFFF', warm: '#1d1d1f' },
  dark: { primary: '#F5F5F5', secondary: '#A8A8A8', tertiary: '#909090', inverse: '#0A0A0A', warm: '#F5EFE6' },
};

const Hairline = {
  light: { hairline: 'rgba(10,10,10,0.06)', soft: 'rgba(10,10,10,0.10)', strong: 'rgba(10,10,10,0.18)' },
  dark: { hairline: 'rgba(255,255,255,0.08)', soft: 'rgba(255,255,255,0.14)', strong: 'rgba(255,255,255,0.24)' },
};

const Semantic = {
  light: { success: '#10B981', warning: '#F59E0B', error: '#EF4444', info: '#3B82F6' },
  dark: { success: '#34D399', warning: '#FBBF24', error: '#F87171', info: '#60A5FA' },
};

const Backdrop = {
  light: 'rgba(0,0,0,0.4)',
  heavy: 'rgba(0,0,0,0.7)',
  lightDark: 'rgba(0,0,0,0.6)',
  heavyDark: 'rgba(0,0,0,0.85)',
};

// DS2.3 — depth locked at 6px. The peak-moment shadow is the Duolingo-
// spirited "press" visual that distinguishes a *designed peak* (cooking
// complete, save to kitchen) from a chrome interaction (cancel, dismiss).
// 4px reads as iOS-native press; 6px reads as joy peak — and Sazon's
// brand voice (DS2.4) is "lifestyle / personality > native feel". See
// docs/design-decisions/DS2.3-peak-depth.md for the rationale.
const PeakShadow = {
  lightColor: '#d67a0c',
  darkColor: '#E07A40',
  depth: 6,
  pressTranslate: 6,
};

// ─── DS3.1 — Chart palette (OkLCh-spaced, 8-series rotation) ─────────────
// Curated to be perceptually distinguishable (ΔE > 12 between adjacent
// pairs). Distinct from the Pastel performers, which are tied to macro
// meaning (sage→protein, blush→sugar) — Chart series have no semantic load.
const Chart = {
  light: {
    series: [
      '#E07A40', // 0 deep coral (warm)
      '#3A8FB7', // 1 muted teal-blue
      '#7AAE5C', // 2 olive green
      '#C75D8F', // 3 dusty rose
      '#9C6BC9', // 4 muted violet
      '#D6A22E', // 5 amber gold
      '#5A8A7C', // 6 sage teal
      '#B85C42', // 7 brick red
    ],
  },
  dark: {
    series: [
      '#FF9559', // 0 brand coral (brightened for dark)
      '#5BB0D8', // 1 brighter teal
      '#A1CC85', // 2 brighter olive
      '#E68AAE', // 3 brighter rose
      '#BB95E0', // 4 brighter violet
      '#F0C055', // 5 brighter amber
      '#85B4A6', // 6 brighter sage
      '#D88A75', // 7 brighter brick
    ],
  },
};

// ─── DS3.2 — Semantic surface tokens (bg / border / ink per level) ───────
const SurfaceSemantic = {
  light: {
    success: { bg: '#D1FAE5', border: '#34D399', ink: '#065F46' },
    warning: { bg: '#FEF3C7', border: '#F59E0B', ink: '#78350F' },
    error: { bg: '#FEE2E2', border: '#EF4444', ink: '#7F1D1D' },
    info: { bg: '#DBEAFE', border: '#3B82F6', ink: '#1E3A8A' },
  },
  dark: {
    success: { bg: '#0E3A2C', border: '#34D399', ink: '#A7F3D0' },
    warning: { bg: '#3D2B0E', border: '#FBBF24', ink: '#FDE68A' },
    error: { bg: '#3D1A1A', border: '#F87171', ink: '#FECACA' },
    info: { bg: '#1A2D4A', border: '#60A5FA', ink: '#BFDBFE' },
  },
};

// ─── DS3.3 — Frosted-glass token (codifies FrostedCard) ──────────────────
const Frost = {
  intensity: 40,
  bg: {
    light: 'rgba(255,255,255,0.64)',
    dark: 'rgba(20,20,20,0.72)',
  },
  border: {
    light: 'rgba(10,10,10,0.06)', // mirrors Hairline.light.hairline
    dark: 'rgba(255,255,255,0.08)', // mirrors Hairline.dark.hairline
  },
};

// ─── DS3.4 — Skeleton / shimmer tokens ───────────────────────────────────
const Skeleton = {
  bg: {
    light: '#EAE6E1', // warm beige idle
    dark: '#1F1A17', // warm cocoa idle
  },
  shimmer: {
    light: '#F5F2EE', // warm cream highlight
    dark: '#2A231F', // brighter cocoa highlight
  },
  durationMs: 1500,
  easing: 'linear',
};

// ─── DS3.5 — Image-loading state tokens ──────────────────────────────────
const ImageState = {
  placeholder: {
    bg: {
      light: '#EAE6E1', // warm-gray for blur-up
      dark: '#1F1A17',
    },
  },
  fallback: {
    mascot: 'curious', // src=undefined → curious mascot card
  },
  error: {
    bg: {
      light: '#FFF0EE', // pastel.red
      dark: '#2E1A1A', // pastel-dark red (DS2.1)
    },
    mascot: 'thinking',
  },
};

module.exports = {
  Canvas,
  Surface,
  Brand,
  PastelTokens,
  AccentTokens,
  Ink,
  Hairline,
  Semantic,
  SurfaceSemantic,
  Backdrop,
  PeakShadow,
  Chart,
  Frost,
  Skeleton,
  ImageState,
};
