// backend/src/services/healthierSwapService.ts
// ROADMAP 4.0 Tier C2 — healthierSwap inline-field surfacing logic.
//
// `RecipeInstruction.healthierSwap` is generated by the AI at recipe-write
// time as a compact JSON string. This service decides — at READ time — whether
// to surface the swap to *this user* based on their gap state. Lifestyle voice:
// invitational ("if you want more fiber, try corn tortillas"), never corrective
// ("you're under fiber").
//
// The default lifestyle user with no nutrition preference signal sees
// nothing — no nudge, no guilt. The data-curious user sees swaps when they
// solve a real problem.

export type HealthierSwapType = 'fiber' | 'protein' | 'calorie';

export interface HealthierSwap {
  type: HealthierSwapType;
  text: string;
  deltaMacro: {
    fiber?: number;
    protein?: number;
    calories?: number;
  };
}

export type NutritionUIDensity = 'minimal' | 'macros' | 'macros + micros' | 'power-user';

/**
 * Parse the raw JSON column off `RecipeInstruction.healthierSwap`. Returns
 * null for any malformed / missing input — callers can short-circuit.
 */
export function parseHealthierSwap(raw: string | null | undefined): HealthierSwap | null {
  if (!raw || typeof raw !== 'string') return null;
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return null;
  }
  if (!parsed || typeof parsed !== 'object') return null;
  const obj = parsed as Record<string, unknown>;
  const type = obj.type;
  const text = obj.text;
  if (type !== 'fiber' && type !== 'protein' && type !== 'calorie') return null;
  if (typeof text !== 'string' || text.length === 0) return null;
  const deltaMacro = (obj.deltaMacro && typeof obj.deltaMacro === 'object') ? obj.deltaMacro : {};
  return {
    type,
    text,
    deltaMacro: {
      fiber: typeof (deltaMacro as any).fiber === 'number' ? (deltaMacro as any).fiber : undefined,
      protein: typeof (deltaMacro as any).protein === 'number' ? (deltaMacro as any).protein : undefined,
      calories: typeof (deltaMacro as any).calories === 'number' ? (deltaMacro as any).calories : undefined,
    },
  };
}

export interface UserSwapState {
  /** Remaining macro budget for the day. Negative = over (already short / past target). */
  remaining: {
    fiber?: number;
    protein?: number;
    calories?: number;
  };
  /** Optional explicit target delta override (currently unused; reserved for advanced opt-ins). */
  targetDelta?: Record<string, number>;
  /** UI density preference from onboarding (governs whether to surface at all). */
  nutritionUIDensity: NutritionUIDensity;
}

/**
 * Returns `true` iff the swap solves a real gap for THIS user.
 *
 * Rules:
 *   - `nutritionUIDensity === 'minimal'` → never surface (user has opted out).
 *   - fiber swap → surface iff remaining.fiber < 0 (user under target).
 *   - protein swap → surface iff remaining.protein < 0.
 *   - calorie swap → surface iff remaining.calories < 0 (over budget).
 */
export function shouldSurfaceSwap(swap: HealthierSwap, userState: UserSwapState): boolean {
  if (userState.nutritionUIDensity === 'minimal') {
    return false;
  }
  const r = userState.remaining;
  switch (swap.type) {
    case 'fiber':
      return typeof r.fiber === 'number' && r.fiber < 0;
    case 'protein':
      return typeof r.protein === 'number' && r.protein < 0;
    case 'calorie':
      return typeof r.calories === 'number' && r.calories < 0;
  }
}

export interface SurfacingDecision {
  surface: boolean;
  swap: HealthierSwap | null;
}

/**
 * One-shot helper: parse the raw column + decide whether to surface, in one call.
 * Use this from the recipe-detail render path.
 */
export function buildSurfacingDecision(
  rawOrSwap: string | HealthierSwap | null,
  userState: UserSwapState
): SurfacingDecision {
  const swap =
    rawOrSwap === null
      ? null
      : typeof rawOrSwap === 'string'
      ? parseHealthierSwap(rawOrSwap)
      : rawOrSwap;
  if (!swap) return { surface: false, swap: null };
  return { surface: shouldSurfaceSwap(swap, userState), swap };
}
