// backend/src/services/mealComponentSeedData.ts
// Group 10X Phase 1 — Build-a-Plate component catalog.
// 125 components: 25 proteins / 15 bases / 50 vegetables / 25 sauces / 10 garnishes.

export interface MealComponentSeed {
  id: string;
  slot: 'protein' | 'base' | 'vegetable' | 'sauce' | 'garnish';
  name: string;
  description: string | null;
  defaultPortionGrams: number;
  caloriesPerPortion: number;
  proteinG: number;
  carbsG: number;
  fatG: number;
  fiberG: number | null;
  estimatedCostPerPortion: number | null;
  cuisineTags: string;
  dietaryTags: string;
  cookMethodHint: 'roast' | 'pan_sear' | 'simmer' | 'raw' | 'mix' | 'grill' | 'bake';
  cookTimeMinutes: number;
  equipmentNeeded: string; // JSON array of equipment tags
  pantryIngredientNames: string;
  imageUrl: string | null;
}

export const SEED_SLOT_COUNTS = {
  protein: 31,
  base: 15,
  vegetable: 50,
  sauce: 25,
  garnish: 10,
} as const;

/**
 * Style tag for the "glazed protein bites" family — soy + honey + sesame +
 * rice vinegar marinade on cubed protein, finished in toaster oven or
 * skillet. The plate builder treats components carrying this tag as
 * interchangeable variants. Tier D recipe-DB generation should produce
 * additional recipes in this style (see plans/plan-archives/ROADMAP_4.0.md tier D notes).
 */
export const GLAZED_BITE_STYLE_TAG = 'glazed_bite';

const tags = (...t: string[]) => JSON.stringify(t);
const ing = (...names: string[]) => JSON.stringify(names);
const eq = (...e: string[]) => JSON.stringify(e);

const PROTEINS: MealComponentSeed[] = [
  { id: 'p_salmon', slot: 'protein', name: 'Salmon Fillet', description: 'Wild-caught salmon, pan-seared.', defaultPortionGrams: 150, caloriesPerPortion: 280, proteinG: 30, carbsG: 0, fatG: 18, fiberG: 0, estimatedCostPerPortion: 5.5, cuisineTags: tags('Mediterranean', 'Japanese'), dietaryTags: tags('gluten_free', 'high_protein', 'pescatarian'), cookMethodHint: 'pan_sear', cookTimeMinutes: 8, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('salmon', 'olive oil', 'lemon', 'salt'), imageUrl: null },
  { id: 'p_chicken_thigh', slot: 'protein', name: 'Chicken Thigh', description: 'Boneless, skin-on.', defaultPortionGrams: 150, caloriesPerPortion: 260, proteinG: 28, carbsG: 0, fatG: 16, fiberG: 0, estimatedCostPerPortion: 2.5, cuisineTags: tags('American', 'Mediterranean', 'Mexican'), dietaryTags: tags('gluten_free', 'high_protein'), cookMethodHint: 'pan_sear', cookTimeMinutes: 12, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('chicken thigh', 'olive oil', 'salt', 'pepper'), imageUrl: null },
  { id: 'p_chicken_breast', slot: 'protein', name: 'Chicken Breast', description: 'Lean, grilled.', defaultPortionGrams: 150, caloriesPerPortion: 230, proteinG: 43, carbsG: 0, fatG: 5, fiberG: 0, estimatedCostPerPortion: 3, cuisineTags: tags('American', 'Mediterranean'), dietaryTags: tags('gluten_free', 'high_protein', 'low_fat'), cookMethodHint: 'grill', cookTimeMinutes: 15, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('chicken breast', 'olive oil', 'salt'), imageUrl: null },
  { id: 'p_ground_beef', slot: 'protein', name: 'Ground Beef (85/15)', description: 'Browned, seasoned.', defaultPortionGrams: 120, caloriesPerPortion: 290, proteinG: 26, carbsG: 0, fatG: 21, fiberG: 0, estimatedCostPerPortion: 3.2, cuisineTags: tags('American', 'Mexican', 'Italian'), dietaryTags: tags('gluten_free', 'high_protein'), cookMethodHint: 'pan_sear', cookTimeMinutes: 10, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('ground beef', 'salt', 'pepper'), imageUrl: null },
  { id: 'p_steak_sirloin', slot: 'protein', name: 'Sirloin Steak', description: 'Pan-seared rare.', defaultPortionGrams: 150, caloriesPerPortion: 320, proteinG: 38, carbsG: 0, fatG: 18, fiberG: 0, estimatedCostPerPortion: 7, cuisineTags: tags('American', 'South American'), dietaryTags: tags('gluten_free', 'high_protein'), cookMethodHint: 'pan_sear', cookTimeMinutes: 8, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('sirloin', 'butter', 'salt', 'pepper'), imageUrl: null },
  { id: 'p_pork_tenderloin', slot: 'protein', name: 'Pork Tenderloin', description: 'Roasted, sliced.', defaultPortionGrams: 150, caloriesPerPortion: 240, proteinG: 36, carbsG: 0, fatG: 9, fiberG: 0, estimatedCostPerPortion: 4, cuisineTags: tags('American', 'Asian'), dietaryTags: tags('gluten_free', 'high_protein', 'low_fat'), cookMethodHint: 'roast', cookTimeMinutes: 25, equipmentNeeded: eq('oven'), pantryIngredientNames: ing('pork tenderloin', 'olive oil', 'salt'), imageUrl: null },
  { id: 'p_shrimp', slot: 'protein', name: 'Shrimp', description: 'Quick-sauteed.', defaultPortionGrams: 120, caloriesPerPortion: 130, proteinG: 24, carbsG: 1, fatG: 2, fiberG: 0, estimatedCostPerPortion: 4.5, cuisineTags: tags('Mediterranean', 'Asian', 'Cajun'), dietaryTags: tags('gluten_free', 'high_protein', 'low_fat', 'pescatarian'), cookMethodHint: 'pan_sear', cookTimeMinutes: 5, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('shrimp', 'butter', 'garlic', 'lemon'), imageUrl: null },
  { id: 'p_tuna_seared', slot: 'protein', name: 'Seared Ahi Tuna', description: 'Rare, sliced.', defaultPortionGrams: 150, caloriesPerPortion: 200, proteinG: 38, carbsG: 0, fatG: 5, fiberG: 0, estimatedCostPerPortion: 8, cuisineTags: tags('Japanese', 'Asian'), dietaryTags: tags('gluten_free', 'high_protein', 'low_fat', 'pescatarian'), cookMethodHint: 'pan_sear', cookTimeMinutes: 4, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('tuna', 'sesame oil', 'soy sauce'), imageUrl: null },
  { id: 'p_cod', slot: 'protein', name: 'Baked Cod', description: 'Flaky white fish.', defaultPortionGrams: 150, caloriesPerPortion: 140, proteinG: 30, carbsG: 0, fatG: 1, fiberG: 0, estimatedCostPerPortion: 5, cuisineTags: tags('Mediterranean', 'European'), dietaryTags: tags('gluten_free', 'high_protein', 'low_fat', 'pescatarian'), cookMethodHint: 'bake', cookTimeMinutes: 15, equipmentNeeded: eq('oven'), pantryIngredientNames: ing('cod', 'olive oil', 'lemon', 'salt'), imageUrl: null },
  { id: 'p_tofu_firm', slot: 'protein', name: 'Crispy Tofu', description: 'Pan-fried firm tofu.', defaultPortionGrams: 150, caloriesPerPortion: 180, proteinG: 18, carbsG: 5, fatG: 11, fiberG: 2, estimatedCostPerPortion: 1.5, cuisineTags: tags('Asian', 'Japanese', 'Chinese'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'high_protein'), cookMethodHint: 'pan_sear', cookTimeMinutes: 12, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('tofu', 'soy sauce', 'cornstarch', 'oil'), imageUrl: null },
  { id: 'p_tempeh', slot: 'protein', name: 'Marinated Tempeh', description: 'Fermented soy, pan-seared.', defaultPortionGrams: 120, caloriesPerPortion: 220, proteinG: 22, carbsG: 11, fatG: 11, fiberG: 6, estimatedCostPerPortion: 3, cuisineTags: tags('Asian', 'Indonesian'), dietaryTags: tags('vegan', 'vegetarian', 'high_protein'), cookMethodHint: 'pan_sear', cookTimeMinutes: 10, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('tempeh', 'soy sauce', 'maple syrup', 'oil'), imageUrl: null },
  { id: 'p_chickpeas_crispy', slot: 'protein', name: 'Crispy Chickpeas', description: 'Roasted with spices.', defaultPortionGrams: 150, caloriesPerPortion: 240, proteinG: 13, carbsG: 36, fatG: 5, fiberG: 10, estimatedCostPerPortion: 1, cuisineTags: tags('Mediterranean', 'Middle Eastern', 'Indian'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'high_fiber'), cookMethodHint: 'roast', cookTimeMinutes: 25, equipmentNeeded: eq('oven'), pantryIngredientNames: ing('chickpeas', 'olive oil', 'paprika', 'salt'), imageUrl: null },
  { id: 'p_lentils_brown', slot: 'protein', name: 'Stewed Brown Lentils', description: 'Earthy and hearty.', defaultPortionGrams: 200, caloriesPerPortion: 230, proteinG: 18, carbsG: 40, fatG: 1, fiberG: 16, estimatedCostPerPortion: 0.8, cuisineTags: tags('Mediterranean', 'Indian', 'Middle Eastern'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'high_protein', 'high_fiber'), cookMethodHint: 'simmer', cookTimeMinutes: 30, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('brown lentils', 'onion', 'garlic', 'olive oil'), imageUrl: null },
  { id: 'p_eggs_scrambled', slot: 'protein', name: 'Soft Scrambled Eggs', description: 'Three large eggs.', defaultPortionGrams: 150, caloriesPerPortion: 220, proteinG: 19, carbsG: 2, fatG: 15, fiberG: 0, estimatedCostPerPortion: 1, cuisineTags: tags('American', 'European'), dietaryTags: tags('vegetarian', 'gluten_free', 'high_protein'), cookMethodHint: 'pan_sear', cookTimeMinutes: 5, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('eggs', 'butter', 'salt'), imageUrl: null },
  { id: 'p_turkey_ground', slot: 'protein', name: 'Ground Turkey', description: '93/7 lean.', defaultPortionGrams: 120, caloriesPerPortion: 200, proteinG: 27, carbsG: 0, fatG: 11, fiberG: 0, estimatedCostPerPortion: 3, cuisineTags: tags('American', 'Mediterranean'), dietaryTags: tags('gluten_free', 'high_protein', 'low_fat'), cookMethodHint: 'pan_sear', cookTimeMinutes: 10, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('ground turkey', 'olive oil', 'salt', 'pepper'), imageUrl: null },
  { id: 'p_lamb_chops', slot: 'protein', name: 'Lamb Chops', description: 'Pan-seared with rosemary.', defaultPortionGrams: 150, caloriesPerPortion: 320, proteinG: 28, carbsG: 0, fatG: 24, fiberG: 0, estimatedCostPerPortion: 9, cuisineTags: tags('Mediterranean', 'Middle Eastern'), dietaryTags: tags('gluten_free', 'high_protein'), cookMethodHint: 'pan_sear', cookTimeMinutes: 10, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('lamb chops', 'rosemary', 'garlic', 'olive oil'), imageUrl: null },
  { id: 'p_duck_breast', slot: 'protein', name: 'Crispy Duck Breast', description: 'Skin-on, scored.', defaultPortionGrams: 150, caloriesPerPortion: 350, proteinG: 32, carbsG: 0, fatG: 24, fiberG: 0, estimatedCostPerPortion: 11, cuisineTags: tags('French', 'Asian'), dietaryTags: tags('gluten_free', 'high_protein'), cookMethodHint: 'pan_sear', cookTimeMinutes: 15, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('duck breast', 'salt', 'pepper'), imageUrl: null },
  { id: 'p_sausage_italian', slot: 'protein', name: 'Italian Sausage', description: 'Browned, sliced.', defaultPortionGrams: 120, caloriesPerPortion: 320, proteinG: 18, carbsG: 2, fatG: 26, fiberG: 0, estimatedCostPerPortion: 3, cuisineTags: tags('Italian', 'American'), dietaryTags: tags('gluten_free', 'high_protein'), cookMethodHint: 'pan_sear', cookTimeMinutes: 12, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('italian sausage', 'olive oil'), imageUrl: null },
  { id: 'p_chorizo', slot: 'protein', name: 'Chorizo', description: 'Smoky Spanish sausage.', defaultPortionGrams: 100, caloriesPerPortion: 280, proteinG: 16, carbsG: 1, fatG: 23, fiberG: 0, estimatedCostPerPortion: 3.5, cuisineTags: tags('Spanish', 'Mexican'), dietaryTags: tags('gluten_free', 'high_protein'), cookMethodHint: 'pan_sear', cookTimeMinutes: 8, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('chorizo'), imageUrl: null },
  { id: 'p_beans_black', slot: 'protein', name: 'Stewed Black Beans', description: 'Cuban-style.', defaultPortionGrams: 200, caloriesPerPortion: 240, proteinG: 15, carbsG: 42, fatG: 1, fiberG: 15, estimatedCostPerPortion: 0.9, cuisineTags: tags('Mexican', 'Latin', 'Cuban'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'high_fiber', 'high_protein'), cookMethodHint: 'simmer', cookTimeMinutes: 20, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('black beans', 'onion', 'garlic', 'cumin'), imageUrl: null },
  { id: 'p_beans_white_cannellini', slot: 'protein', name: 'Cannellini Beans', description: 'Tuscan-style.', defaultPortionGrams: 200, caloriesPerPortion: 230, proteinG: 14, carbsG: 40, fatG: 1, fiberG: 12, estimatedCostPerPortion: 0.9, cuisineTags: tags('Italian', 'Mediterranean'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'high_fiber', 'high_protein'), cookMethodHint: 'simmer', cookTimeMinutes: 20, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('cannellini beans', 'olive oil', 'rosemary', 'garlic'), imageUrl: null },
  { id: 'p_seitan', slot: 'protein', name: 'Seitan', description: 'Wheat protein, browned.', defaultPortionGrams: 120, caloriesPerPortion: 200, proteinG: 30, carbsG: 12, fatG: 2, fiberG: 1, estimatedCostPerPortion: 3, cuisineTags: tags('Asian', 'American'), dietaryTags: tags('vegan', 'vegetarian', 'high_protein'), cookMethodHint: 'pan_sear', cookTimeMinutes: 8, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('seitan', 'soy sauce', 'oil'), imageUrl: null },
  { id: 'p_paneer', slot: 'protein', name: 'Paneer', description: 'Indian fresh cheese, cubed.', defaultPortionGrams: 120, caloriesPerPortion: 320, proteinG: 22, carbsG: 4, fatG: 25, fiberG: 0, estimatedCostPerPortion: 3, cuisineTags: tags('Indian'), dietaryTags: tags('vegetarian', 'gluten_free', 'high_protein'), cookMethodHint: 'pan_sear', cookTimeMinutes: 8, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('paneer', 'oil', 'turmeric'), imageUrl: null },
  { id: 'p_halloumi', slot: 'protein', name: 'Grilled Halloumi', description: 'Salty squeak cheese.', defaultPortionGrams: 100, caloriesPerPortion: 320, proteinG: 22, carbsG: 2, fatG: 25, fiberG: 0, estimatedCostPerPortion: 4, cuisineTags: tags('Mediterranean', 'Middle Eastern'), dietaryTags: tags('vegetarian', 'gluten_free', 'high_protein'), cookMethodHint: 'grill', cookTimeMinutes: 6, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('halloumi', 'olive oil'), imageUrl: null },
  { id: 'p_edamame', slot: 'protein', name: 'Steamed Edamame', description: 'Salted soybeans.', defaultPortionGrams: 150, caloriesPerPortion: 180, proteinG: 17, carbsG: 14, fatG: 8, fiberG: 8, estimatedCostPerPortion: 2, cuisineTags: tags('Japanese', 'Asian'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'high_protein', 'high_fiber'), cookMethodHint: 'simmer', cookTimeMinutes: 8, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('edamame', 'salt'), imageUrl: null },

  // ── Glazed protein bites — soy + honey + sesame + rice vinegar family.
  // Cubed protein (1-1.5"), short marinade, toaster-oven or skillet finish.
  // All carry the 'glazed_bite' style tag; the plate builder treats them
  // as interchangeable variants. Macros are per 150g cooked portion (the
  // plate builder's default protein portion); marinade calories included.
  { id: 'p_salmon_bites_asian_glaze', slot: 'protein', name: 'Salmon Bites (Asian Glaze)', description: 'Cubed salmon in soy-honey-sesame glaze; toaster-oven 12-15 min.', defaultPortionGrams: 150, caloriesPerPortion: 385, proteinG: 33, carbsG: 8, fatG: 23, fiberG: 0, estimatedCostPerPortion: 5.5, cuisineTags: tags('Asian', 'Japanese', GLAZED_BITE_STYLE_TAG), dietaryTags: tags('gluten_free_swap', 'high_protein', 'pescatarian'), cookMethodHint: 'roast', cookTimeMinutes: 15, equipmentNeeded: eq('toaster_oven', 'oven'), pantryIngredientNames: ing('salmon', 'soy sauce', 'honey', 'sesame oil', 'rice vinegar', 'garlic', 'ginger', 'sesame seeds'), imageUrl: null },
  { id: 'p_chicken_bites_asian_glaze', slot: 'protein', name: 'Chicken Bites (Asian Glaze)', description: 'Cubed chicken breast in soy-honey-sesame glaze; toaster-oven 18-22 min or skillet.', defaultPortionGrams: 150, caloriesPerPortion: 270, proteinG: 33, carbsG: 12, fatG: 6, fiberG: 0, estimatedCostPerPortion: 3.2, cuisineTags: tags('Asian', GLAZED_BITE_STYLE_TAG), dietaryTags: tags('gluten_free_swap', 'high_protein', 'low_fat'), cookMethodHint: 'roast', cookTimeMinutes: 20, equipmentNeeded: eq('toaster_oven', 'oven', 'stovetop_burner'), pantryIngredientNames: ing('chicken breast', 'soy sauce', 'honey', 'sesame oil', 'rice vinegar', 'cornstarch', 'garlic', 'ginger', 'sesame seeds'), imageUrl: null },
  { id: 'p_tofu_bites_asian_glaze', slot: 'protein', name: 'Tofu Bites (Asian Glaze)', description: 'Pressed extra-firm tofu cubes in soy-honey-sesame glaze; toaster-oven 18-20 min.', defaultPortionGrams: 150, caloriesPerPortion: 250, proteinG: 22, carbsG: 14, fatG: 12, fiberG: 1, estimatedCostPerPortion: 1.8, cuisineTags: tags('Asian', GLAZED_BITE_STYLE_TAG), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free_swap', 'high_protein'), cookMethodHint: 'roast', cookTimeMinutes: 20, equipmentNeeded: eq('toaster_oven', 'oven'), pantryIngredientNames: ing('extra-firm tofu', 'soy sauce', 'honey', 'sesame oil', 'rice vinegar', 'cornstarch', 'garlic', 'ginger'), imageUrl: null },
  { id: 'p_shrimp_bites_asian_glaze', slot: 'protein', name: 'Shrimp Bites (Asian Glaze)', description: 'Peeled shrimp tossed in soy-honey-sesame glaze; skillet 4-5 min.', defaultPortionGrams: 150, caloriesPerPortion: 220, proteinG: 30, carbsG: 10, fatG: 5, fiberG: 0, estimatedCostPerPortion: 5, cuisineTags: tags('Asian', 'Japanese', GLAZED_BITE_STYLE_TAG), dietaryTags: tags('gluten_free_swap', 'high_protein', 'low_fat', 'pescatarian'), cookMethodHint: 'pan_sear', cookTimeMinutes: 5, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('shrimp', 'soy sauce', 'honey', 'sesame oil', 'rice vinegar', 'garlic', 'ginger'), imageUrl: null },
  { id: 'p_tempeh_bites_asian_glaze', slot: 'protein', name: 'Tempeh Bites (Asian Glaze)', description: 'Cubed tempeh in soy-honey-sesame glaze; toaster-oven 20 min.', defaultPortionGrams: 150, caloriesPerPortion: 320, proteinG: 28, carbsG: 18, fatG: 14, fiberG: 6, estimatedCostPerPortion: 2.5, cuisineTags: tags('Asian', 'Indonesian', GLAZED_BITE_STYLE_TAG), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free_swap', 'high_protein', 'high_fiber'), cookMethodHint: 'roast', cookTimeMinutes: 20, equipmentNeeded: eq('toaster_oven', 'oven'), pantryIngredientNames: ing('tempeh', 'soy sauce', 'honey', 'sesame oil', 'rice vinegar', 'garlic', 'ginger'), imageUrl: null },
  { id: 'p_pork_tenderloin_bites_asian_glaze', slot: 'protein', name: 'Pork Tenderloin Bites (Asian Glaze)', description: 'Cubed pork tenderloin in soy-honey-sesame glaze; skillet 6-8 min.', defaultPortionGrams: 150, caloriesPerPortion: 295, proteinG: 35, carbsG: 11, fatG: 10, fiberG: 0, estimatedCostPerPortion: 4.5, cuisineTags: tags('Asian', 'American', GLAZED_BITE_STYLE_TAG), dietaryTags: tags('gluten_free_swap', 'high_protein'), cookMethodHint: 'pan_sear', cookTimeMinutes: 8, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('pork tenderloin', 'soy sauce', 'honey', 'sesame oil', 'rice vinegar', 'cornstarch', 'garlic', 'ginger'), imageUrl: null },
];

const BASES: MealComponentSeed[] = [
  { id: 'b_brown_rice', slot: 'base', name: 'Brown Rice', description: 'Nutty whole grain.', defaultPortionGrams: 200, caloriesPerPortion: 220, proteinG: 5, carbsG: 46, fatG: 2, fiberG: 4, estimatedCostPerPortion: 0.5, cuisineTags: tags('Asian', 'American'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'whole_grain'), cookMethodHint: 'simmer', cookTimeMinutes: 40, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('brown rice', 'salt'), imageUrl: null },
  { id: 'b_white_rice', slot: 'base', name: 'Jasmine Rice', description: 'Fragrant long-grain.', defaultPortionGrams: 200, caloriesPerPortion: 240, proteinG: 4, carbsG: 53, fatG: 0, fiberG: 1, estimatedCostPerPortion: 0.4, cuisineTags: tags('Asian', 'Thai'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free'), cookMethodHint: 'simmer', cookTimeMinutes: 18, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('jasmine rice', 'salt'), imageUrl: null },
  { id: 'b_farro', slot: 'base', name: 'Farro', description: 'Chewy ancient grain.', defaultPortionGrams: 200, caloriesPerPortion: 230, proteinG: 8, carbsG: 47, fatG: 1, fiberG: 6, estimatedCostPerPortion: 1, cuisineTags: tags('Italian', 'Mediterranean'), dietaryTags: tags('vegan', 'vegetarian', 'whole_grain', 'high_fiber'), cookMethodHint: 'simmer', cookTimeMinutes: 30, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('farro', 'salt', 'olive oil'), imageUrl: null },
  { id: 'b_quinoa', slot: 'base', name: 'Quinoa', description: 'Complete protein grain.', defaultPortionGrams: 200, caloriesPerPortion: 220, proteinG: 8, carbsG: 39, fatG: 4, fiberG: 5, estimatedCostPerPortion: 1.2, cuisineTags: tags('South American', 'Mediterranean'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'high_protein', 'high_fiber'), cookMethodHint: 'simmer', cookTimeMinutes: 15, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('quinoa', 'salt'), imageUrl: null },
  { id: 'b_barley', slot: 'base', name: 'Pearled Barley', description: 'Toothsome grain.', defaultPortionGrams: 200, caloriesPerPortion: 200, proteinG: 7, carbsG: 44, fatG: 1, fiberG: 6, estimatedCostPerPortion: 0.6, cuisineTags: tags('European', 'Mediterranean'), dietaryTags: tags('vegan', 'vegetarian', 'whole_grain', 'high_fiber'), cookMethodHint: 'simmer', cookTimeMinutes: 35, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('barley', 'salt'), imageUrl: null },
  { id: 'b_couscous', slot: 'base', name: 'Pearl Couscous', description: 'Toasted pearls.', defaultPortionGrams: 200, caloriesPerPortion: 220, proteinG: 8, carbsG: 44, fatG: 1, fiberG: 3, estimatedCostPerPortion: 0.8, cuisineTags: tags('Mediterranean', 'Middle Eastern', 'North African'), dietaryTags: tags('vegan', 'vegetarian'), cookMethodHint: 'simmer', cookTimeMinutes: 10, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('pearl couscous', 'olive oil', 'salt'), imageUrl: null },
  { id: 'b_sweet_potato', slot: 'base', name: 'Roasted Sweet Potato', description: 'Caramelized cubes.', defaultPortionGrams: 200, caloriesPerPortion: 180, proteinG: 4, carbsG: 41, fatG: 0, fiberG: 6, estimatedCostPerPortion: 0.7, cuisineTags: tags('American', 'Caribbean'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'high_fiber', 'paleo'), cookMethodHint: 'roast', cookTimeMinutes: 30, equipmentNeeded: eq('oven'), pantryIngredientNames: ing('sweet potato', 'olive oil', 'salt'), imageUrl: null },
  { id: 'b_potato_baby', slot: 'base', name: 'Roasted Baby Potatoes', description: 'Crispy edges.', defaultPortionGrams: 200, caloriesPerPortion: 200, proteinG: 5, carbsG: 44, fatG: 1, fiberG: 4, estimatedCostPerPortion: 0.5, cuisineTags: tags('American', 'European'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free'), cookMethodHint: 'roast', cookTimeMinutes: 30, equipmentNeeded: eq('oven'), pantryIngredientNames: ing('baby potatoes', 'olive oil', 'salt', 'rosemary'), imageUrl: null },
  { id: 'b_polenta', slot: 'base', name: 'Creamy Polenta', description: 'Stone-ground corn.', defaultPortionGrams: 200, caloriesPerPortion: 240, proteinG: 6, carbsG: 38, fatG: 7, fiberG: 3, estimatedCostPerPortion: 0.7, cuisineTags: tags('Italian'), dietaryTags: tags('vegetarian', 'gluten_free'), cookMethodHint: 'simmer', cookTimeMinutes: 20, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('polenta', 'butter', 'parmesan', 'salt'), imageUrl: null },
  { id: 'b_pasta_whole_wheat', slot: 'base', name: 'Whole Wheat Pasta', description: 'Al dente.', defaultPortionGrams: 200, caloriesPerPortion: 260, proteinG: 12, carbsG: 52, fatG: 2, fiberG: 8, estimatedCostPerPortion: 0.8, cuisineTags: tags('Italian'), dietaryTags: tags('vegan', 'vegetarian', 'whole_grain', 'high_fiber'), cookMethodHint: 'simmer', cookTimeMinutes: 12, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('whole wheat pasta', 'salt'), imageUrl: null },
  { id: 'b_soba', slot: 'base', name: 'Soba Noodles', description: 'Buckwheat, chilled or warm.', defaultPortionGrams: 200, caloriesPerPortion: 220, proteinG: 9, carbsG: 47, fatG: 1, fiberG: 4, estimatedCostPerPortion: 1.5, cuisineTags: tags('Japanese', 'Asian'), dietaryTags: tags('vegan', 'vegetarian'), cookMethodHint: 'simmer', cookTimeMinutes: 8, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('soba noodles', 'salt'), imageUrl: null },
  { id: 'b_rice_noodles', slot: 'base', name: 'Rice Noodles', description: 'Silky and quick.', defaultPortionGrams: 200, caloriesPerPortion: 220, proteinG: 4, carbsG: 50, fatG: 0, fiberG: 1, estimatedCostPerPortion: 1, cuisineTags: tags('Asian', 'Thai', 'Vietnamese'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free'), cookMethodHint: 'simmer', cookTimeMinutes: 5, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('rice noodles'), imageUrl: null },
  { id: 'b_tortilla_corn', slot: 'base', name: 'Warmed Corn Tortillas', description: 'Charred lightly.', defaultPortionGrams: 100, caloriesPerPortion: 200, proteinG: 5, carbsG: 41, fatG: 2, fiberG: 5, estimatedCostPerPortion: 0.6, cuisineTags: tags('Mexican', 'Latin'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free'), cookMethodHint: 'pan_sear', cookTimeMinutes: 3, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('corn tortillas'), imageUrl: null },
  { id: 'b_flatbread_naan', slot: 'base', name: 'Warm Naan', description: 'Soft and pillowy.', defaultPortionGrams: 100, caloriesPerPortion: 280, proteinG: 8, carbsG: 50, fatG: 5, fiberG: 2, estimatedCostPerPortion: 1, cuisineTags: tags('Indian', 'Middle Eastern'), dietaryTags: tags('vegetarian'), cookMethodHint: 'bake', cookTimeMinutes: 8, equipmentNeeded: eq('oven'), pantryIngredientNames: ing('naan', 'butter'), imageUrl: null },
  { id: 'b_cauliflower_rice', slot: 'base', name: 'Cauliflower Rice', description: 'Riced and sauteed.', defaultPortionGrams: 200, caloriesPerPortion: 60, proteinG: 4, carbsG: 10, fatG: 1, fiberG: 4, estimatedCostPerPortion: 1.2, cuisineTags: tags('American', 'Mediterranean'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'low_carb', 'paleo', 'keto'), cookMethodHint: 'pan_sear', cookTimeMinutes: 8, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('cauliflower', 'olive oil', 'salt'), imageUrl: null },
];

const VEG_DEFS: Array<Omit<MealComponentSeed, 'slot'>> = [
  { id: 'v_roasted_carrots', name: 'Roasted Carrots', description: 'Caramelized with cumin.', defaultPortionGrams: 150, caloriesPerPortion: 100, proteinG: 1, carbsG: 18, fatG: 4, fiberG: 5, estimatedCostPerPortion: 0.5, cuisineTags: tags('Mediterranean', 'American'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'high_fiber', 'paleo'), cookMethodHint: 'roast', cookTimeMinutes: 25, equipmentNeeded: eq('oven'), pantryIngredientNames: ing('carrots', 'olive oil', 'cumin', 'salt'), imageUrl: null },
  { id: 'v_roasted_broccoli', name: 'Charred Broccoli', description: 'High-heat blistered.', defaultPortionGrams: 150, caloriesPerPortion: 90, proteinG: 4, carbsG: 10, fatG: 5, fiberG: 4, estimatedCostPerPortion: 1, cuisineTags: tags('American', 'Mediterranean'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'high_fiber', 'paleo'), cookMethodHint: 'roast', cookTimeMinutes: 20, equipmentNeeded: eq('oven'), pantryIngredientNames: ing('broccoli', 'olive oil', 'salt'), imageUrl: null },
  { id: 'v_roasted_brussels', name: 'Crispy Brussels Sprouts', description: 'Charred outside, tender inside.', defaultPortionGrams: 150, caloriesPerPortion: 110, proteinG: 4, carbsG: 12, fatG: 6, fiberG: 5, estimatedCostPerPortion: 1.5, cuisineTags: tags('American', 'European'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'high_fiber'), cookMethodHint: 'roast', cookTimeMinutes: 25, equipmentNeeded: eq('oven'), pantryIngredientNames: ing('brussels sprouts', 'olive oil', 'salt'), imageUrl: null },
  { id: 'v_roasted_cauliflower', name: 'Roasted Cauliflower', description: 'Golden florets.', defaultPortionGrams: 150, caloriesPerPortion: 100, proteinG: 3, carbsG: 9, fatG: 6, fiberG: 4, estimatedCostPerPortion: 1.2, cuisineTags: tags('Mediterranean', 'Indian'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'low_carb'), cookMethodHint: 'roast', cookTimeMinutes: 25, equipmentNeeded: eq('oven'), pantryIngredientNames: ing('cauliflower', 'olive oil', 'turmeric', 'salt'), imageUrl: null },
  { id: 'v_sauteed_spinach', name: 'Wilted Spinach', description: 'Garlic and lemon.', defaultPortionGrams: 100, caloriesPerPortion: 70, proteinG: 3, carbsG: 5, fatG: 5, fiberG: 3, estimatedCostPerPortion: 1, cuisineTags: tags('Mediterranean', 'Italian'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'low_carb', 'paleo'), cookMethodHint: 'pan_sear', cookTimeMinutes: 5, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('spinach', 'garlic', 'olive oil'), imageUrl: null },
  { id: 'v_sauteed_kale', name: 'Crispy Kale', description: 'Lightly charred.', defaultPortionGrams: 100, caloriesPerPortion: 80, proteinG: 3, carbsG: 8, fatG: 5, fiberG: 4, estimatedCostPerPortion: 1.2, cuisineTags: tags('American', 'Mediterranean'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free'), cookMethodHint: 'pan_sear', cookTimeMinutes: 8, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('kale', 'olive oil', 'garlic', 'salt'), imageUrl: null },
  { id: 'v_grilled_zucchini', name: 'Grilled Zucchini', description: 'Smoky and tender.', defaultPortionGrams: 150, caloriesPerPortion: 80, proteinG: 2, carbsG: 8, fatG: 5, fiberG: 3, estimatedCostPerPortion: 0.8, cuisineTags: tags('Mediterranean', 'Italian'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'low_carb'), cookMethodHint: 'grill', cookTimeMinutes: 8, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('zucchini', 'olive oil', 'salt'), imageUrl: null },
  { id: 'v_grilled_eggplant', name: 'Grilled Eggplant', description: 'Silky and smoky.', defaultPortionGrams: 150, caloriesPerPortion: 100, proteinG: 2, carbsG: 12, fatG: 6, fiberG: 5, estimatedCostPerPortion: 1, cuisineTags: tags('Mediterranean', 'Middle Eastern'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free'), cookMethodHint: 'grill', cookTimeMinutes: 10, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('eggplant', 'olive oil', 'salt'), imageUrl: null },
  { id: 'v_roasted_bell_pepper', name: 'Blistered Bell Peppers', description: 'Sweet and charred.', defaultPortionGrams: 150, caloriesPerPortion: 80, proteinG: 1, carbsG: 12, fatG: 4, fiberG: 4, estimatedCostPerPortion: 1, cuisineTags: tags('Mediterranean', 'Mexican'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free'), cookMethodHint: 'roast', cookTimeMinutes: 20, equipmentNeeded: eq('oven'), pantryIngredientNames: ing('bell pepper', 'olive oil', 'salt'), imageUrl: null },
  { id: 'v_roasted_squash', name: 'Roasted Butternut Squash', description: 'Maple-spiced.', defaultPortionGrams: 200, caloriesPerPortion: 130, proteinG: 2, carbsG: 24, fatG: 4, fiberG: 5, estimatedCostPerPortion: 1.5, cuisineTags: tags('American', 'European'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'high_fiber'), cookMethodHint: 'roast', cookTimeMinutes: 30, equipmentNeeded: eq('oven'), pantryIngredientNames: ing('butternut squash', 'olive oil', 'maple syrup', 'salt'), imageUrl: null },
  { id: 'v_sauteed_mushrooms', name: 'Garlic Mushrooms', description: 'Browned and savory.', defaultPortionGrams: 150, caloriesPerPortion: 110, proteinG: 4, carbsG: 7, fatG: 8, fiberG: 2, estimatedCostPerPortion: 2, cuisineTags: tags('European', 'American'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'low_carb'), cookMethodHint: 'pan_sear', cookTimeMinutes: 10, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('mushrooms', 'butter', 'garlic', 'thyme'), imageUrl: null },
  { id: 'v_roasted_asparagus', name: 'Roasted Asparagus', description: 'Lemon and pepper.', defaultPortionGrams: 150, caloriesPerPortion: 90, proteinG: 4, carbsG: 7, fatG: 5, fiberG: 4, estimatedCostPerPortion: 2, cuisineTags: tags('Mediterranean', 'European'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'low_carb', 'paleo'), cookMethodHint: 'roast', cookTimeMinutes: 15, equipmentNeeded: eq('oven'), pantryIngredientNames: ing('asparagus', 'olive oil', 'lemon', 'salt'), imageUrl: null },
  { id: 'v_roasted_green_beans', name: 'Blistered Green Beans', description: 'Snappy and charred.', defaultPortionGrams: 150, caloriesPerPortion: 80, proteinG: 3, carbsG: 9, fatG: 4, fiberG: 4, estimatedCostPerPortion: 1.2, cuisineTags: tags('American', 'Asian'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'low_carb'), cookMethodHint: 'roast', cookTimeMinutes: 15, equipmentNeeded: eq('oven'), pantryIngredientNames: ing('green beans', 'olive oil', 'garlic', 'salt'), imageUrl: null },
  { id: 'v_steamed_bok_choy', name: 'Steamed Bok Choy', description: 'Garlic-ginger drizzle.', defaultPortionGrams: 150, caloriesPerPortion: 60, proteinG: 3, carbsG: 5, fatG: 3, fiberG: 2, estimatedCostPerPortion: 1.2, cuisineTags: tags('Asian', 'Chinese'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'low_carb'), cookMethodHint: 'simmer', cookTimeMinutes: 5, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('bok choy', 'garlic', 'ginger', 'sesame oil'), imageUrl: null },
  { id: 'v_roasted_beets', name: 'Roasted Beets', description: 'Earthy and sweet.', defaultPortionGrams: 150, caloriesPerPortion: 100, proteinG: 3, carbsG: 18, fatG: 3, fiberG: 5, estimatedCostPerPortion: 1.5, cuisineTags: tags('European', 'Mediterranean'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'high_fiber'), cookMethodHint: 'roast', cookTimeMinutes: 45, equipmentNeeded: eq('oven'), pantryIngredientNames: ing('beets', 'olive oil', 'salt'), imageUrl: null },
  { id: 'v_grilled_corn', name: 'Charred Corn', description: 'Sweet kernels off the cob.', defaultPortionGrams: 150, caloriesPerPortion: 130, proteinG: 4, carbsG: 28, fatG: 2, fiberG: 4, estimatedCostPerPortion: 1, cuisineTags: tags('American', 'Mexican'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free'), cookMethodHint: 'grill', cookTimeMinutes: 10, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('corn', 'butter', 'salt'), imageUrl: null },
  { id: 'v_roasted_tomatoes', name: 'Slow-Roasted Tomatoes', description: 'Concentrated and sweet.', defaultPortionGrams: 150, caloriesPerPortion: 100, proteinG: 2, carbsG: 10, fatG: 7, fiberG: 3, estimatedCostPerPortion: 1.2, cuisineTags: tags('Mediterranean', 'Italian'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'low_carb'), cookMethodHint: 'roast', cookTimeMinutes: 45, equipmentNeeded: eq('oven'), pantryIngredientNames: ing('tomatoes', 'olive oil', 'garlic', 'thyme'), imageUrl: null },
  { id: 'v_pickled_red_onion', name: 'Quick-Pickled Red Onion', description: 'Bright and crunchy.', defaultPortionGrams: 50, caloriesPerPortion: 30, proteinG: 0, carbsG: 7, fatG: 0, fiberG: 1, estimatedCostPerPortion: 0.4, cuisineTags: tags('Mexican', 'Mediterranean'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'low_carb'), cookMethodHint: 'raw', cookTimeMinutes: 0, equipmentNeeded: eq('none'), pantryIngredientNames: ing('red onion', 'vinegar', 'sugar', 'salt'), imageUrl: null },
  { id: 'v_arugula_salad', name: 'Arugula Salad', description: 'Peppery, lemon-dressed.', defaultPortionGrams: 80, caloriesPerPortion: 70, proteinG: 1, carbsG: 4, fatG: 6, fiberG: 1, estimatedCostPerPortion: 1.5, cuisineTags: tags('Italian', 'Mediterranean'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'low_carb'), cookMethodHint: 'raw', cookTimeMinutes: 0, equipmentNeeded: eq('none'), pantryIngredientNames: ing('arugula', 'olive oil', 'lemon'), imageUrl: null },
  { id: 'v_cucumber_salad', name: 'Cucumber Salad', description: 'Cool and crisp.', defaultPortionGrams: 100, caloriesPerPortion: 50, proteinG: 1, carbsG: 6, fatG: 3, fiberG: 1, estimatedCostPerPortion: 1, cuisineTags: tags('Asian', 'Mediterranean'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'low_carb'), cookMethodHint: 'raw', cookTimeMinutes: 0, equipmentNeeded: eq('none'), pantryIngredientNames: ing('cucumber', 'rice vinegar', 'sesame oil'), imageUrl: null },
  { id: 'v_kimchi', name: 'Kimchi', description: 'Fermented Korean cabbage.', defaultPortionGrams: 60, caloriesPerPortion: 30, proteinG: 1, carbsG: 6, fatG: 0, fiberG: 2, estimatedCostPerPortion: 1.5, cuisineTags: tags('Korean', 'Asian'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'low_carb', 'fermented'), cookMethodHint: 'raw', cookTimeMinutes: 0, equipmentNeeded: eq('none'), pantryIngredientNames: ing('kimchi'), imageUrl: null },
  { id: 'v_sauerkraut', name: 'Sauerkraut', description: 'Fermented cabbage tang.', defaultPortionGrams: 60, caloriesPerPortion: 20, proteinG: 1, carbsG: 4, fatG: 0, fiberG: 3, estimatedCostPerPortion: 1, cuisineTags: tags('European', 'German'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'low_carb', 'fermented'), cookMethodHint: 'raw', cookTimeMinutes: 0, equipmentNeeded: eq('none'), pantryIngredientNames: ing('sauerkraut'), imageUrl: null },
  { id: 'v_sliced_avocado', name: 'Sliced Avocado', description: 'Buttery half.', defaultPortionGrams: 80, caloriesPerPortion: 130, proteinG: 2, carbsG: 7, fatG: 12, fiberG: 5, estimatedCostPerPortion: 1.5, cuisineTags: tags('Mexican', 'American'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'low_carb', 'paleo', 'keto'), cookMethodHint: 'raw', cookTimeMinutes: 0, equipmentNeeded: eq('none'), pantryIngredientNames: ing('avocado', 'lemon', 'salt'), imageUrl: null },
  { id: 'v_roasted_carrots_bell', name: 'Roasted Carrots + Bell Pepper', description: 'Sweet duo.', defaultPortionGrams: 200, caloriesPerPortion: 140, proteinG: 2, carbsG: 22, fatG: 6, fiberG: 6, estimatedCostPerPortion: 1.2, cuisineTags: tags('Mediterranean'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'high_fiber'), cookMethodHint: 'roast', cookTimeMinutes: 25, equipmentNeeded: eq('oven'), pantryIngredientNames: ing('carrots', 'bell pepper', 'olive oil', 'salt'), imageUrl: null },
  { id: 'v_carrot_pepper_spinach', name: 'Carrots + Bell Pepper + Spinach', description: 'Tri-color sauté.', defaultPortionGrams: 200, caloriesPerPortion: 150, proteinG: 4, carbsG: 22, fatG: 6, fiberG: 6, estimatedCostPerPortion: 1.5, cuisineTags: tags('Mediterranean', 'American'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'high_fiber'), cookMethodHint: 'pan_sear', cookTimeMinutes: 10, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('carrots', 'bell pepper', 'spinach', 'olive oil'), imageUrl: null },
  { id: 'v_broccoli_garlic_sesame', name: 'Broccoli + Garlic + Sesame', description: 'Asian-style stir-fry.', defaultPortionGrams: 200, caloriesPerPortion: 130, proteinG: 5, carbsG: 12, fatG: 8, fiberG: 5, estimatedCostPerPortion: 1.5, cuisineTags: tags('Asian', 'Chinese'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free'), cookMethodHint: 'pan_sear', cookTimeMinutes: 8, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('broccoli', 'garlic', 'sesame oil', 'soy sauce'), imageUrl: null },
  { id: 'v_squash_kale_combo', name: 'Squash + Kale Combo', description: 'Autumn pairing.', defaultPortionGrams: 200, caloriesPerPortion: 160, proteinG: 4, carbsG: 26, fatG: 5, fiberG: 6, estimatedCostPerPortion: 2, cuisineTags: tags('American', 'Mediterranean'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'high_fiber'), cookMethodHint: 'roast', cookTimeMinutes: 30, equipmentNeeded: eq('oven'), pantryIngredientNames: ing('butternut squash', 'kale', 'olive oil', 'salt'), imageUrl: null },
  { id: 'v_pepper_onion_fajita', name: 'Fajita Peppers + Onions', description: 'Smoky pepper-onion mix.', defaultPortionGrams: 200, caloriesPerPortion: 110, proteinG: 2, carbsG: 18, fatG: 4, fiberG: 4, estimatedCostPerPortion: 1.2, cuisineTags: tags('Mexican'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free'), cookMethodHint: 'pan_sear', cookTimeMinutes: 12, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('bell pepper', 'onion', 'olive oil', 'cumin'), imageUrl: null },
  { id: 'v_zucchini_tomato_basil', name: 'Zucchini + Tomato + Basil', description: 'Summer ratatouille.', defaultPortionGrams: 200, caloriesPerPortion: 130, proteinG: 3, carbsG: 14, fatG: 7, fiberG: 4, estimatedCostPerPortion: 1.8, cuisineTags: tags('Italian', 'Mediterranean', 'French'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free'), cookMethodHint: 'pan_sear', cookTimeMinutes: 12, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('zucchini', 'tomatoes', 'basil', 'olive oil'), imageUrl: null },
  { id: 'v_mushroom_thyme', name: 'Thyme Mushrooms', description: 'Earthy and herby.', defaultPortionGrams: 150, caloriesPerPortion: 110, proteinG: 4, carbsG: 7, fatG: 8, fiberG: 2, estimatedCostPerPortion: 2, cuisineTags: tags('French', 'European'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'low_carb'), cookMethodHint: 'pan_sear', cookTimeMinutes: 10, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('mushrooms', 'thyme', 'olive oil'), imageUrl: null },
  { id: 'v_radish_butter', name: 'Butter Radishes', description: 'Crisp and salty.', defaultPortionGrams: 80, caloriesPerPortion: 70, proteinG: 1, carbsG: 4, fatG: 5, fiberG: 2, estimatedCostPerPortion: 1, cuisineTags: tags('French'), dietaryTags: tags('vegetarian', 'gluten_free', 'low_carb'), cookMethodHint: 'raw', cookTimeMinutes: 0, equipmentNeeded: eq('none'), pantryIngredientNames: ing('radishes', 'butter', 'salt'), imageUrl: null },
  { id: 'v_snap_peas', name: 'Sugar Snap Peas', description: 'Quick-blanched.', defaultPortionGrams: 100, caloriesPerPortion: 70, proteinG: 3, carbsG: 11, fatG: 1, fiberG: 4, estimatedCostPerPortion: 1.5, cuisineTags: tags('Asian', 'American'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free'), cookMethodHint: 'pan_sear', cookTimeMinutes: 4, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('snap peas', 'salt'), imageUrl: null },
  { id: 'v_okra_charred', name: 'Charred Okra', description: 'Indian-style.', defaultPortionGrams: 150, caloriesPerPortion: 100, proteinG: 3, carbsG: 12, fatG: 5, fiberG: 5, estimatedCostPerPortion: 2, cuisineTags: tags('Indian', 'Southern'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'high_fiber'), cookMethodHint: 'pan_sear', cookTimeMinutes: 10, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('okra', 'olive oil', 'cumin'), imageUrl: null },
  { id: 'v_cabbage_seared', name: 'Seared Cabbage Wedges', description: 'Caramelized edges.', defaultPortionGrams: 200, caloriesPerPortion: 100, proteinG: 3, carbsG: 14, fatG: 5, fiberG: 5, estimatedCostPerPortion: 0.8, cuisineTags: tags('European', 'American'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'low_carb'), cookMethodHint: 'pan_sear', cookTimeMinutes: 12, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('cabbage', 'olive oil', 'salt'), imageUrl: null },
  { id: 'v_fennel_braised', name: 'Braised Fennel', description: 'Anise-tinged.', defaultPortionGrams: 150, caloriesPerPortion: 90, proteinG: 2, carbsG: 11, fatG: 5, fiberG: 4, estimatedCostPerPortion: 2, cuisineTags: tags('Italian', 'Mediterranean'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'low_carb'), cookMethodHint: 'simmer', cookTimeMinutes: 20, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('fennel', 'olive oil', 'salt'), imageUrl: null },
  { id: 'v_leeks_braised', name: 'Braised Leeks', description: 'Silky and sweet.', defaultPortionGrams: 150, caloriesPerPortion: 110, proteinG: 2, carbsG: 16, fatG: 5, fiberG: 3, estimatedCostPerPortion: 2, cuisineTags: tags('French', 'European'), dietaryTags: tags('vegetarian', 'gluten_free'), cookMethodHint: 'simmer', cookTimeMinutes: 15, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('leeks', 'butter', 'salt'), imageUrl: null },
  { id: 'v_beet_carrot_roast', name: 'Roasted Beets + Carrots', description: 'Earthy roots duo.', defaultPortionGrams: 200, caloriesPerPortion: 160, proteinG: 3, carbsG: 28, fatG: 5, fiberG: 7, estimatedCostPerPortion: 2, cuisineTags: tags('European', 'Mediterranean'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'high_fiber'), cookMethodHint: 'roast', cookTimeMinutes: 40, equipmentNeeded: eq('oven'), pantryIngredientNames: ing('beets', 'carrots', 'olive oil', 'thyme'), imageUrl: null },
  { id: 'v_eggplant_chili', name: 'Sichuan Eggplant', description: 'Chili-garlic glaze.', defaultPortionGrams: 200, caloriesPerPortion: 160, proteinG: 3, carbsG: 18, fatG: 9, fiberG: 6, estimatedCostPerPortion: 2, cuisineTags: tags('Chinese', 'Asian'), dietaryTags: tags('vegan', 'vegetarian'), cookMethodHint: 'pan_sear', cookTimeMinutes: 12, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('eggplant', 'soy sauce', 'chili paste', 'garlic'), imageUrl: null },
  { id: 'v_cauliflower_curry', name: 'Curried Cauliflower', description: 'Turmeric-spiced.', defaultPortionGrams: 200, caloriesPerPortion: 130, proteinG: 4, carbsG: 12, fatG: 8, fiberG: 5, estimatedCostPerPortion: 1.5, cuisineTags: tags('Indian'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'low_carb'), cookMethodHint: 'roast', cookTimeMinutes: 25, equipmentNeeded: eq('oven'), pantryIngredientNames: ing('cauliflower', 'curry powder', 'olive oil', 'salt'), imageUrl: null },
  { id: 'v_collards_braised', name: 'Braised Collard Greens', description: 'Smoky Southern style.', defaultPortionGrams: 150, caloriesPerPortion: 90, proteinG: 4, carbsG: 9, fatG: 5, fiberG: 5, estimatedCostPerPortion: 1.5, cuisineTags: tags('Southern', 'American'), dietaryTags: tags('vegetarian', 'gluten_free'), cookMethodHint: 'simmer', cookTimeMinutes: 20, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('collard greens', 'garlic', 'olive oil'), imageUrl: null },
  { id: 'v_swiss_chard_sauteed', name: 'Sautéed Swiss Chard', description: 'Garlicky greens.', defaultPortionGrams: 150, caloriesPerPortion: 80, proteinG: 3, carbsG: 7, fatG: 5, fiberG: 3, estimatedCostPerPortion: 1.5, cuisineTags: tags('Italian', 'Mediterranean'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'low_carb'), cookMethodHint: 'pan_sear', cookTimeMinutes: 8, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('swiss chard', 'garlic', 'olive oil'), imageUrl: null },
  { id: 'v_caprese_tomato', name: 'Tomato Caprese Stack', description: 'Tomato + basil.', defaultPortionGrams: 150, caloriesPerPortion: 100, proteinG: 2, carbsG: 8, fatG: 7, fiberG: 2, estimatedCostPerPortion: 2, cuisineTags: tags('Italian', 'Mediterranean'), dietaryTags: tags('vegetarian', 'gluten_free'), cookMethodHint: 'raw', cookTimeMinutes: 0, equipmentNeeded: eq('none'), pantryIngredientNames: ing('tomatoes', 'basil', 'olive oil', 'balsamic'), imageUrl: null },
  { id: 'v_artichoke_hearts', name: 'Marinated Artichoke Hearts', description: 'Briny and tender.', defaultPortionGrams: 100, caloriesPerPortion: 100, proteinG: 3, carbsG: 9, fatG: 7, fiberG: 5, estimatedCostPerPortion: 2.5, cuisineTags: tags('Italian', 'Mediterranean'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'low_carb'), cookMethodHint: 'raw', cookTimeMinutes: 0, equipmentNeeded: eq('none'), pantryIngredientNames: ing('artichoke hearts', 'olive oil', 'lemon'), imageUrl: null },
  { id: 'v_chickpea_salad', name: 'Mediterranean Chickpea Salad', description: 'Cucumber + tomato + feta.', defaultPortionGrams: 200, caloriesPerPortion: 220, proteinG: 8, carbsG: 22, fatG: 11, fiberG: 6, estimatedCostPerPortion: 2.5, cuisineTags: tags('Mediterranean', 'Greek'), dietaryTags: tags('vegetarian', 'gluten_free', 'high_fiber'), cookMethodHint: 'raw', cookTimeMinutes: 0, equipmentNeeded: eq('none'), pantryIngredientNames: ing('chickpeas', 'cucumber', 'tomatoes', 'feta', 'olive oil'), imageUrl: null },
  { id: 'v_corn_black_bean', name: 'Corn + Black Bean Salad', description: 'Mexican street style.', defaultPortionGrams: 200, caloriesPerPortion: 200, proteinG: 8, carbsG: 32, fatG: 5, fiberG: 8, estimatedCostPerPortion: 1.5, cuisineTags: tags('Mexican', 'Latin'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'high_fiber'), cookMethodHint: 'raw', cookTimeMinutes: 0, equipmentNeeded: eq('none'), pantryIngredientNames: ing('corn', 'black beans', 'lime', 'cilantro'), imageUrl: null },
  { id: 'v_slaw_red_cabbage', name: 'Red Cabbage Slaw', description: 'Crunchy and tangy.', defaultPortionGrams: 100, caloriesPerPortion: 80, proteinG: 2, carbsG: 10, fatG: 4, fiberG: 3, estimatedCostPerPortion: 1, cuisineTags: tags('American', 'Mexican'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free'), cookMethodHint: 'raw', cookTimeMinutes: 0, equipmentNeeded: eq('none'), pantryIngredientNames: ing('red cabbage', 'vinegar', 'olive oil'), imageUrl: null },
  { id: 'v_grilled_romaine', name: 'Grilled Romaine', description: 'Smoky lettuce hearts.', defaultPortionGrams: 100, caloriesPerPortion: 80, proteinG: 2, carbsG: 5, fatG: 6, fiberG: 2, estimatedCostPerPortion: 1.5, cuisineTags: tags('American'), dietaryTags: tags('vegetarian', 'gluten_free', 'low_carb'), cookMethodHint: 'grill', cookTimeMinutes: 4, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('romaine', 'olive oil', 'salt'), imageUrl: null },
  { id: 'v_butternut_kale_quinoa', name: 'Butternut + Kale + Pomegranate', description: 'Festive autumn mix.', defaultPortionGrams: 200, caloriesPerPortion: 180, proteinG: 4, carbsG: 28, fatG: 6, fiberG: 6, estimatedCostPerPortion: 2.5, cuisineTags: tags('Mediterranean', 'American'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'high_fiber'), cookMethodHint: 'roast', cookTimeMinutes: 30, equipmentNeeded: eq('oven'), pantryIngredientNames: ing('butternut squash', 'kale', 'pomegranate', 'olive oil'), imageUrl: null },
  { id: 'v_celery_apple_slaw', name: 'Celery + Apple Slaw', description: 'Bright and crunchy.', defaultPortionGrams: 100, caloriesPerPortion: 70, proteinG: 1, carbsG: 14, fatG: 1, fiberG: 3, estimatedCostPerPortion: 1.5, cuisineTags: tags('American', 'European'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free'), cookMethodHint: 'raw', cookTimeMinutes: 0, equipmentNeeded: eq('none'), pantryIngredientNames: ing('celery', 'apple', 'lemon'), imageUrl: null },
  { id: 'v_broccolini_lemon', name: 'Broccolini with Lemon', description: 'Quick-blistered.', defaultPortionGrams: 150, caloriesPerPortion: 100, proteinG: 4, carbsG: 9, fatG: 6, fiberG: 4, estimatedCostPerPortion: 2, cuisineTags: tags('Italian', 'Mediterranean'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'low_carb'), cookMethodHint: 'roast', cookTimeMinutes: 12, equipmentNeeded: eq('oven'), pantryIngredientNames: ing('broccolini', 'olive oil', 'lemon', 'garlic'), imageUrl: null },
];

const VEGETABLES: MealComponentSeed[] = VEG_DEFS.map((v) => ({ ...v, slot: 'vegetable' as const }));

const SAUCES: MealComponentSeed[] = [
  { id: 's_yogurt_lemon', slot: 'sauce', name: 'Yogurt + Lemon + Butter', description: 'Creamy and bright.', defaultPortionGrams: 60, caloriesPerPortion: 90, proteinG: 4, carbsG: 5, fatG: 6, fiberG: 0, estimatedCostPerPortion: 0.6, cuisineTags: tags('Mediterranean', 'Middle Eastern'), dietaryTags: tags('vegetarian', 'gluten_free'), cookMethodHint: 'mix', cookTimeMinutes: 5, equipmentNeeded: eq('mixing_bowl'), pantryIngredientNames: ing('greek yogurt', 'lemon', 'butter'), imageUrl: null },
  { id: 's_chimichurri', slot: 'sauce', name: 'Chimichurri', description: 'Parsley, garlic, olive oil.', defaultPortionGrams: 50, caloriesPerPortion: 130, proteinG: 1, carbsG: 2, fatG: 13, fiberG: 1, estimatedCostPerPortion: 1, cuisineTags: tags('South American', 'Argentinian'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'low_carb'), cookMethodHint: 'mix', cookTimeMinutes: 5, equipmentNeeded: eq('mixing_bowl'), pantryIngredientNames: ing('parsley', 'garlic', 'olive oil', 'red wine vinegar'), imageUrl: null },
  { id: 's_peanut_sauce', slot: 'sauce', name: 'Peanut Sauce', description: 'Creamy and spicy.', defaultPortionGrams: 50, caloriesPerPortion: 150, proteinG: 5, carbsG: 8, fatG: 11, fiberG: 1, estimatedCostPerPortion: 0.8, cuisineTags: tags('Asian', 'Thai'), dietaryTags: tags('vegan', 'vegetarian'), cookMethodHint: 'mix', cookTimeMinutes: 5, equipmentNeeded: eq('mixing_bowl'), pantryIngredientNames: ing('peanut butter', 'soy sauce', 'lime', 'ginger'), imageUrl: null },
  { id: 's_tahini_lemon', slot: 'sauce', name: 'Tahini + Lemon', description: 'Nutty and bright.', defaultPortionGrams: 50, caloriesPerPortion: 130, proteinG: 4, carbsG: 5, fatG: 11, fiberG: 2, estimatedCostPerPortion: 1, cuisineTags: tags('Middle Eastern', 'Mediterranean'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free'), cookMethodHint: 'mix', cookTimeMinutes: 5, equipmentNeeded: eq('mixing_bowl'), pantryIngredientNames: ing('tahini', 'lemon', 'garlic'), imageUrl: null },
  { id: 's_pesto', slot: 'sauce', name: 'Basil Pesto', description: 'Bright herb sauce.', defaultPortionGrams: 50, caloriesPerPortion: 180, proteinG: 4, carbsG: 3, fatG: 17, fiberG: 1, estimatedCostPerPortion: 1.5, cuisineTags: tags('Italian'), dietaryTags: tags('vegetarian', 'gluten_free'), cookMethodHint: 'mix', cookTimeMinutes: 5, equipmentNeeded: eq('mixing_bowl'), pantryIngredientNames: ing('basil', 'pine nuts', 'parmesan', 'olive oil'), imageUrl: null },
  { id: 's_salsa_verde', slot: 'sauce', name: 'Salsa Verde', description: 'Tomatillo and cilantro.', defaultPortionGrams: 60, caloriesPerPortion: 50, proteinG: 1, carbsG: 6, fatG: 3, fiberG: 1, estimatedCostPerPortion: 1, cuisineTags: tags('Mexican'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'low_carb'), cookMethodHint: 'mix', cookTimeMinutes: 5, equipmentNeeded: eq('mixing_bowl'), pantryIngredientNames: ing('tomatillos', 'cilantro', 'lime', 'jalapeño'), imageUrl: null },
  { id: 's_salsa_roja', slot: 'sauce', name: 'Salsa Roja', description: 'Smoky tomato salsa.', defaultPortionGrams: 60, caloriesPerPortion: 50, proteinG: 1, carbsG: 8, fatG: 2, fiberG: 2, estimatedCostPerPortion: 1, cuisineTags: tags('Mexican'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'low_carb'), cookMethodHint: 'mix', cookTimeMinutes: 5, equipmentNeeded: eq('mixing_bowl'), pantryIngredientNames: ing('tomatoes', 'chipotle', 'lime'), imageUrl: null },
  { id: 's_chili_crisp', slot: 'sauce', name: 'Chili Crisp', description: 'Crunchy umami heat.', defaultPortionGrams: 30, caloriesPerPortion: 90, proteinG: 1, carbsG: 4, fatG: 8, fiberG: 1, estimatedCostPerPortion: 0.8, cuisineTags: tags('Chinese', 'Asian'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free'), cookMethodHint: 'mix', cookTimeMinutes: 0, equipmentNeeded: eq('none'), pantryIngredientNames: ing('chili crisp'), imageUrl: null },
  { id: 's_soy_ginger', slot: 'sauce', name: 'Soy Ginger Glaze', description: 'Salty-sweet umami.', defaultPortionGrams: 50, caloriesPerPortion: 70, proteinG: 2, carbsG: 12, fatG: 1, fiberG: 0, estimatedCostPerPortion: 0.5, cuisineTags: tags('Asian', 'Japanese'), dietaryTags: tags('vegan', 'vegetarian'), cookMethodHint: 'mix', cookTimeMinutes: 5, equipmentNeeded: eq('mixing_bowl'), pantryIngredientNames: ing('soy sauce', 'ginger', 'honey', 'rice vinegar'), imageUrl: null },
  { id: 's_miso_butter', slot: 'sauce', name: 'Miso Butter', description: 'Umami compound butter.', defaultPortionGrams: 30, caloriesPerPortion: 130, proteinG: 1, carbsG: 2, fatG: 13, fiberG: 0, estimatedCostPerPortion: 1, cuisineTags: tags('Japanese', 'Asian'), dietaryTags: tags('vegetarian'), cookMethodHint: 'mix', cookTimeMinutes: 3, equipmentNeeded: eq('mixing_bowl'), pantryIngredientNames: ing('miso', 'butter'), imageUrl: null },
  { id: 's_harissa_yogurt', slot: 'sauce', name: 'Harissa Yogurt', description: 'Smoky-spicy creamy.', defaultPortionGrams: 60, caloriesPerPortion: 80, proteinG: 4, carbsG: 5, fatG: 5, fiberG: 0, estimatedCostPerPortion: 0.8, cuisineTags: tags('North African', 'Middle Eastern'), dietaryTags: tags('vegetarian', 'gluten_free'), cookMethodHint: 'mix', cookTimeMinutes: 5, equipmentNeeded: eq('mixing_bowl'), pantryIngredientNames: ing('greek yogurt', 'harissa', 'lemon'), imageUrl: null },
  { id: 's_tzatziki', slot: 'sauce', name: 'Tzatziki', description: 'Cucumber-yogurt.', defaultPortionGrams: 60, caloriesPerPortion: 70, proteinG: 4, carbsG: 5, fatG: 4, fiberG: 0, estimatedCostPerPortion: 0.8, cuisineTags: tags('Greek', 'Mediterranean'), dietaryTags: tags('vegetarian', 'gluten_free'), cookMethodHint: 'mix', cookTimeMinutes: 5, equipmentNeeded: eq('mixing_bowl'), pantryIngredientNames: ing('greek yogurt', 'cucumber', 'garlic', 'dill'), imageUrl: null },
  { id: 's_aioli_garlic', slot: 'sauce', name: 'Garlic Aioli', description: 'Mayo-based, garlicky.', defaultPortionGrams: 40, caloriesPerPortion: 180, proteinG: 0, carbsG: 1, fatG: 19, fiberG: 0, estimatedCostPerPortion: 0.7, cuisineTags: tags('Mediterranean', 'Spanish'), dietaryTags: tags('vegetarian', 'gluten_free'), cookMethodHint: 'mix', cookTimeMinutes: 3, equipmentNeeded: eq('mixing_bowl'), pantryIngredientNames: ing('mayo', 'garlic', 'lemon'), imageUrl: null },
  { id: 's_sriracha_mayo', slot: 'sauce', name: 'Sriracha Mayo', description: 'Spicy creamy drizzle.', defaultPortionGrams: 40, caloriesPerPortion: 160, proteinG: 0, carbsG: 2, fatG: 17, fiberG: 0, estimatedCostPerPortion: 0.5, cuisineTags: tags('Asian', 'American'), dietaryTags: tags('vegetarian', 'gluten_free'), cookMethodHint: 'mix', cookTimeMinutes: 2, equipmentNeeded: eq('mixing_bowl'), pantryIngredientNames: ing('mayo', 'sriracha', 'lime'), imageUrl: null },
  { id: 's_lemon_butter', slot: 'sauce', name: 'Lemon Butter', description: 'Bright pan sauce.', defaultPortionGrams: 30, caloriesPerPortion: 110, proteinG: 0, carbsG: 1, fatG: 12, fiberG: 0, estimatedCostPerPortion: 0.5, cuisineTags: tags('French', 'Mediterranean'), dietaryTags: tags('vegetarian', 'gluten_free', 'low_carb'), cookMethodHint: 'mix', cookTimeMinutes: 3, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('butter', 'lemon', 'parsley'), imageUrl: null },
  { id: 's_balsamic_glaze', slot: 'sauce', name: 'Balsamic Glaze', description: 'Sweet-tart reduction.', defaultPortionGrams: 30, caloriesPerPortion: 50, proteinG: 0, carbsG: 12, fatG: 0, fiberG: 0, estimatedCostPerPortion: 0.5, cuisineTags: tags('Italian'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'low_fat'), cookMethodHint: 'mix', cookTimeMinutes: 0, equipmentNeeded: eq('none'), pantryIngredientNames: ing('balsamic vinegar', 'honey'), imageUrl: null },
  { id: 's_avocado_crema', slot: 'sauce', name: 'Avocado Crema', description: 'Creamy and lime-bright.', defaultPortionGrams: 50, caloriesPerPortion: 110, proteinG: 1, carbsG: 5, fatG: 10, fiberG: 3, estimatedCostPerPortion: 1, cuisineTags: tags('Mexican', 'Latin'), dietaryTags: tags('vegetarian', 'gluten_free'), cookMethodHint: 'mix', cookTimeMinutes: 5, equipmentNeeded: eq('mixing_bowl'), pantryIngredientNames: ing('avocado', 'sour cream', 'lime', 'cilantro'), imageUrl: null },
  { id: 's_curry_coconut', slot: 'sauce', name: 'Coconut Curry', description: 'Rich and aromatic.', defaultPortionGrams: 80, caloriesPerPortion: 160, proteinG: 2, carbsG: 8, fatG: 14, fiberG: 1, estimatedCostPerPortion: 1.5, cuisineTags: tags('Thai', 'Indian', 'Asian'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free'), cookMethodHint: 'simmer', cookTimeMinutes: 15, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('coconut milk', 'curry paste', 'lime'), imageUrl: null },
  { id: 's_marinara', slot: 'sauce', name: 'Marinara', description: 'Slow-simmered tomato.', defaultPortionGrams: 80, caloriesPerPortion: 80, proteinG: 2, carbsG: 12, fatG: 3, fiberG: 3, estimatedCostPerPortion: 0.7, cuisineTags: tags('Italian'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free'), cookMethodHint: 'simmer', cookTimeMinutes: 20, equipmentNeeded: eq('stovetop_burner'), pantryIngredientNames: ing('tomatoes', 'garlic', 'basil', 'olive oil'), imageUrl: null },
  { id: 's_romesco', slot: 'sauce', name: 'Romesco', description: 'Smoky pepper-almond.', defaultPortionGrams: 50, caloriesPerPortion: 140, proteinG: 3, carbsG: 7, fatG: 12, fiberG: 2, estimatedCostPerPortion: 1.5, cuisineTags: tags('Spanish', 'Mediterranean'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free'), cookMethodHint: 'mix', cookTimeMinutes: 5, equipmentNeeded: eq('mixing_bowl'), pantryIngredientNames: ing('roasted red peppers', 'almonds', 'garlic', 'olive oil'), imageUrl: null },
  { id: 's_gochujang_glaze', slot: 'sauce', name: 'Gochujang Glaze', description: 'Sweet-spicy Korean.', defaultPortionGrams: 50, caloriesPerPortion: 90, proteinG: 1, carbsG: 18, fatG: 1, fiberG: 1, estimatedCostPerPortion: 0.7, cuisineTags: tags('Korean', 'Asian'), dietaryTags: tags('vegan', 'vegetarian'), cookMethodHint: 'mix', cookTimeMinutes: 5, equipmentNeeded: eq('mixing_bowl'), pantryIngredientNames: ing('gochujang', 'soy sauce', 'sesame oil', 'honey'), imageUrl: null },
  { id: 's_mojo_verde', slot: 'sauce', name: 'Mojo Verde', description: 'Bright Canarian green.', defaultPortionGrams: 50, caloriesPerPortion: 120, proteinG: 1, carbsG: 3, fatG: 12, fiberG: 1, estimatedCostPerPortion: 1, cuisineTags: tags('Spanish', 'Latin'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free'), cookMethodHint: 'mix', cookTimeMinutes: 5, equipmentNeeded: eq('mixing_bowl'), pantryIngredientNames: ing('cilantro', 'garlic', 'olive oil', 'lime'), imageUrl: null },
  { id: 's_apple_mustard', slot: 'sauce', name: 'Apple Mustard', description: 'Sweet-tangy.', defaultPortionGrams: 30, caloriesPerPortion: 60, proteinG: 1, carbsG: 12, fatG: 1, fiberG: 1, estimatedCostPerPortion: 0.6, cuisineTags: tags('European', 'American'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free'), cookMethodHint: 'mix', cookTimeMinutes: 3, equipmentNeeded: eq('mixing_bowl'), pantryIngredientNames: ing('dijon mustard', 'apple cider vinegar', 'honey'), imageUrl: null },
  { id: 's_ginger_scallion', slot: 'sauce', name: 'Ginger Scallion', description: 'Bright and aromatic.', defaultPortionGrams: 40, caloriesPerPortion: 110, proteinG: 1, carbsG: 3, fatG: 11, fiberG: 1, estimatedCostPerPortion: 0.8, cuisineTags: tags('Chinese', 'Asian'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free'), cookMethodHint: 'mix', cookTimeMinutes: 5, equipmentNeeded: eq('mixing_bowl'), pantryIngredientNames: ing('ginger', 'scallions', 'oil', 'salt'), imageUrl: null },
  { id: 's_hot_honey', slot: 'sauce', name: 'Hot Honey', description: 'Sweet-spicy drizzle.', defaultPortionGrams: 25, caloriesPerPortion: 70, proteinG: 0, carbsG: 18, fatG: 0, fiberG: 0, estimatedCostPerPortion: 0.5, cuisineTags: tags('American', 'Italian'), dietaryTags: tags('vegetarian', 'gluten_free', 'low_fat'), cookMethodHint: 'mix', cookTimeMinutes: 0, equipmentNeeded: eq('none'), pantryIngredientNames: ing('honey', 'chili flakes'), imageUrl: null },
];

const GARNISHES: MealComponentSeed[] = [
  { id: 'g_toasted_sesame', slot: 'garnish', name: 'Toasted Sesame Seeds', description: 'Nutty crunch.', defaultPortionGrams: 8, caloriesPerPortion: 50, proteinG: 2, carbsG: 2, fatG: 4, fiberG: 1, estimatedCostPerPortion: 0.2, cuisineTags: tags('Asian', 'Japanese'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free'), cookMethodHint: 'mix', cookTimeMinutes: 0, equipmentNeeded: eq('none'), pantryIngredientNames: ing('sesame seeds'), imageUrl: null },
  { id: 'g_pomegranate', slot: 'garnish', name: 'Pomegranate Seeds', description: 'Jewel-bright pop.', defaultPortionGrams: 30, caloriesPerPortion: 40, proteinG: 1, carbsG: 9, fatG: 0, fiberG: 2, estimatedCostPerPortion: 1, cuisineTags: tags('Middle Eastern', 'Mediterranean'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'low_fat'), cookMethodHint: 'raw', cookTimeMinutes: 0, equipmentNeeded: eq('none'), pantryIngredientNames: ing('pomegranate'), imageUrl: null },
  { id: 'g_pickled_jalapeno', slot: 'garnish', name: 'Pickled Jalapeños', description: 'Tangy heat.', defaultPortionGrams: 20, caloriesPerPortion: 10, proteinG: 0, carbsG: 2, fatG: 0, fiberG: 1, estimatedCostPerPortion: 0.3, cuisineTags: tags('Mexican'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'low_fat'), cookMethodHint: 'raw', cookTimeMinutes: 0, equipmentNeeded: eq('none'), pantryIngredientNames: ing('pickled jalapeños'), imageUrl: null },
  { id: 'g_cilantro', slot: 'garnish', name: 'Fresh Cilantro', description: 'Bright green.', defaultPortionGrams: 10, caloriesPerPortion: 5, proteinG: 0, carbsG: 1, fatG: 0, fiberG: 0, estimatedCostPerPortion: 0.2, cuisineTags: tags('Mexican', 'Asian', 'Latin'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'low_fat'), cookMethodHint: 'raw', cookTimeMinutes: 0, equipmentNeeded: eq('none'), pantryIngredientNames: ing('cilantro'), imageUrl: null },
  { id: 'g_basil_chiffonade', slot: 'garnish', name: 'Basil Chiffonade', description: 'Fragrant ribbons.', defaultPortionGrams: 5, caloriesPerPortion: 5, proteinG: 0, carbsG: 1, fatG: 0, fiberG: 0, estimatedCostPerPortion: 0.3, cuisineTags: tags('Italian', 'Mediterranean'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'low_fat'), cookMethodHint: 'raw', cookTimeMinutes: 0, equipmentNeeded: eq('none'), pantryIngredientNames: ing('basil'), imageUrl: null },
  { id: 'g_crispy_shallot', slot: 'garnish', name: 'Crispy Fried Shallots', description: 'Savory crunch.', defaultPortionGrams: 15, caloriesPerPortion: 80, proteinG: 1, carbsG: 7, fatG: 6, fiberG: 1, estimatedCostPerPortion: 0.5, cuisineTags: tags('Asian', 'Vietnamese'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free'), cookMethodHint: 'mix', cookTimeMinutes: 0, equipmentNeeded: eq('none'), pantryIngredientNames: ing('shallots', 'oil'), imageUrl: null },
  { id: 'g_feta_crumble', slot: 'garnish', name: 'Crumbled Feta', description: 'Briny and creamy.', defaultPortionGrams: 20, caloriesPerPortion: 60, proteinG: 4, carbsG: 1, fatG: 5, fiberG: 0, estimatedCostPerPortion: 0.7, cuisineTags: tags('Greek', 'Mediterranean'), dietaryTags: tags('vegetarian', 'gluten_free'), cookMethodHint: 'raw', cookTimeMinutes: 0, equipmentNeeded: eq('none'), pantryIngredientNames: ing('feta'), imageUrl: null },
  { id: 'g_parm_shavings', slot: 'garnish', name: 'Parmesan Shavings', description: 'Salty umami.', defaultPortionGrams: 15, caloriesPerPortion: 60, proteinG: 5, carbsG: 1, fatG: 4, fiberG: 0, estimatedCostPerPortion: 0.8, cuisineTags: tags('Italian'), dietaryTags: tags('vegetarian', 'gluten_free'), cookMethodHint: 'raw', cookTimeMinutes: 0, equipmentNeeded: eq('none'), pantryIngredientNames: ing('parmesan'), imageUrl: null },
  { id: 'g_pine_nuts', slot: 'garnish', name: 'Toasted Pine Nuts', description: 'Buttery nutty crunch.', defaultPortionGrams: 15, caloriesPerPortion: 100, proteinG: 2, carbsG: 2, fatG: 10, fiberG: 1, estimatedCostPerPortion: 1.5, cuisineTags: tags('Italian', 'Mediterranean'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free'), cookMethodHint: 'mix', cookTimeMinutes: 0, equipmentNeeded: eq('none'), pantryIngredientNames: ing('pine nuts'), imageUrl: null },
  { id: 'g_lemon_zest', slot: 'garnish', name: 'Lemon Zest', description: 'Bright aromatic oil.', defaultPortionGrams: 5, caloriesPerPortion: 5, proteinG: 0, carbsG: 1, fatG: 0, fiberG: 0, estimatedCostPerPortion: 0.2, cuisineTags: tags('Mediterranean', 'European'), dietaryTags: tags('vegan', 'vegetarian', 'gluten_free', 'low_fat'), cookMethodHint: 'raw', cookTimeMinutes: 0, equipmentNeeded: eq('none'), pantryIngredientNames: ing('lemon'), imageUrl: null },
];

export const MEAL_COMPONENT_SEED: ReadonlyArray<MealComponentSeed> = [
  ...PROTEINS,
  ...BASES,
  ...VEGETABLES,
  ...SAUCES,
  ...GARNISHES,
];
