// backend/src/services/sazonQuipService.ts
// ROADMAP 4.0 Tier J7 — Sazon daily quip.
//
// One rotating culinary aphorism / cuisine proverb / kitchen wisdom line at the
// top of Today, rotating daily (deterministic by day-of-year). Lifestyle voice:
// no verdict tone, no bodybuilder/macro-cult vocabulary.

export type QuipCategory = 'proverb' | 'observation' | 'personality';

export interface SazonQuip {
  id: string;
  text: string;
  category: QuipCategory;
}

export const BANNED_VOCAB = [
  'macro-friendly',
  'cut phase',
  'bulk phase',
  'maintain phase',
  'cutting phase',
  'bulking phase',
];

const PROVERBS: SazonQuip[] = [
  { id: 'p001', text: 'In Italy, the cook who waits has the best dough.', category: 'proverb' },
  { id: 'p002', text: 'A French kitchen is not a place — it is a discipline.', category: 'proverb' },
  { id: 'p003', text: 'Japanese knives reward respect; they punish hurry.', category: 'proverb' },
  { id: 'p004', text: 'In Mexico, the molcajete remembers every salsa it has ever held.', category: 'proverb' },
  { id: 'p005', text: 'A Lebanese table is never set for the number you invited.', category: 'proverb' },
  { id: 'p006', text: 'In Persia, rice is not a side — it is the centerpiece dressed up as one.', category: 'proverb' },
  { id: 'p007', text: 'A Thai cook seasons four ways and tastes five times.', category: 'proverb' },
  { id: 'p008', text: 'In Korea, the side dishes outnumber the courses, and that is the point.', category: 'proverb' },
  { id: 'p009', text: 'An Ethiopian meal is shared with the right hand and a generous heart.', category: 'proverb' },
  { id: 'p010', text: 'A Vietnamese broth is judged by how clear it stays after twelve hours.', category: 'proverb' },
  { id: 'p011', text: 'In Spain, dinner is a conversation that happens to involve food.', category: 'proverb' },
  { id: 'p012', text: 'A Greek grandmother measures olive oil in glugs, not spoons.', category: 'proverb' },
  { id: 'p013', text: 'In India, the spice goes in twice — once for color, once for soul.', category: 'proverb' },
  { id: 'p014', text: 'A Turkish breakfast can last until lunch, and often does.', category: 'proverb' },
  { id: 'p015', text: 'In Morocco, the tagine cooks itself if you let it.', category: 'proverb' },
  { id: 'p016', text: 'A Filipino kitchen runs on vinegar, garlic, and timing.', category: 'proverb' },
  { id: 'p017', text: 'In China, the wok is older than the stove — and it has opinions.', category: 'proverb' },
  { id: 'p018', text: 'A Salvadorean cook never serves a pupusa without curtido.', category: 'proverb' },
  { id: 'p019', text: 'In Peru, the ceviche is dressed at the last possible moment.', category: 'proverb' },
  { id: 'p020', text: 'A Cajun roux is brown when it smells like a memory.', category: 'proverb' },
  { id: 'p021', text: 'In Sicily, the tomato is treated like family — gently and often.', category: 'proverb' },
  { id: 'p022', text: 'A Burmese tea leaf salad is built, not tossed.', category: 'proverb' },
  { id: 'p023', text: 'In Ghana, jollof rice is a regional argument that everyone wins.', category: 'proverb' },
  { id: 'p024', text: 'A Brazilian feijoada simmers all day so the table can sit longer.', category: 'proverb' },
  { id: 'p025', text: 'In Argentina, the asado is led by fire, not by the cook.', category: 'proverb' },
  { id: 'p026', text: 'A Chilean kitchen always has a lemon nearby.', category: 'proverb' },
  { id: 'p027', text: 'In Lebanon, the host eats last — and serves twice.', category: 'proverb' },
  { id: 'p028', text: 'A Polish pierogi is folded with the patience the meal will repay.', category: 'proverb' },
  { id: 'p029', text: 'In Hungary, paprika is a season, not a spice.', category: 'proverb' },
  { id: 'p030', text: 'A Norwegian fish does not need a marinade — it needs respect.', category: 'proverb' },
  { id: 'p031', text: 'In Iceland, the bread is baked in the ground and the patience is geological.', category: 'proverb' },
  { id: 'p032', text: 'A Senegalese thieboudienne is the meal the rest of the week is planned around.', category: 'proverb' },
  { id: 'p033', text: 'In Egypt, ful medames is breakfast, lunch, and the answer to "what now?"', category: 'proverb' },
  { id: 'p034', text: 'A Nigerian jollof is finished with smoke from the bottom of the pot.', category: 'proverb' },
  { id: 'p035', text: 'In Kenya, ugali is the spoon you can eat.', category: 'proverb' },
  { id: 'p036', text: 'A Ukrainian borscht turns ruby when the love is in early.', category: 'proverb' },
  { id: 'p037', text: 'In Georgia, khachapuri is folded around the egg like a promise.', category: 'proverb' },
  { id: 'p038', text: 'A Russian table without bread is a table that has forgotten itself.', category: 'proverb' },
  { id: 'p039', text: 'In Indonesia, sambal is built before the meal is even imagined.', category: 'proverb' },
  { id: 'p040', text: 'A Malaysian laksa is the broth your other broths apologize to.', category: 'proverb' },
  { id: 'p041', text: 'In Sri Lanka, the curry leaves go in whole — they are not a garnish.', category: 'proverb' },
  { id: 'p042', text: 'A Pakistani biryani is layered in silence because it knows what it is.', category: 'proverb' },
  { id: 'p043', text: 'In Bangladesh, the fish stew remembers every river it ever swam.', category: 'proverb' },
  { id: 'p044', text: 'A Nepali dal bhat reminds the body what enough feels like.', category: 'proverb' },
  { id: 'p045', text: 'In Tibet, momos are folded clockwise, because that is how the day goes.', category: 'proverb' },
  { id: 'p046', text: 'A Mongolian khorkhog cooks with stones that are older than the recipe.', category: 'proverb' },
  { id: 'p047', text: 'In Cambodia, the prahok is small but the meal is built around it.', category: 'proverb' },
  { id: 'p048', text: 'A Laotian larb tastes like the herbs were picked five minutes ago — because they were.', category: 'proverb' },
  { id: 'p049', text: 'In Okinawa, the pork is slow, the bitter melon is brave, and the centenarians keep cooking.', category: 'proverb' },
  { id: 'p050', text: 'A Cuban moros y cristianos is a story told in two grains.', category: 'proverb' },
  { id: 'p051', text: 'In Puerto Rico, sofrito is the first thing the kitchen smells in the morning.', category: 'proverb' },
  { id: 'p052', text: 'A Dominican sancocho is for the day a family decides to come home.', category: 'proverb' },
  { id: 'p053', text: 'In Haiti, griot is fried twice for two reasons — texture, and the second is patience.', category: 'proverb' },
  { id: 'p054', text: 'A Jamaican jerk is a slow argument between heat and time.', category: 'proverb' },
  { id: 'p055', text: 'In Bolivia, the saltena is folded against gravity and against the clock.', category: 'proverb' },
  { id: 'p056', text: 'A Colombian arepa is judged by the corn, not by the filling.', category: 'proverb' },
  { id: 'p057', text: 'In Venezuela, the cachapa is sweet because the corn was just cut.', category: 'proverb' },
  { id: 'p058', text: 'A Uruguayan asado runs on hardwood, conversation, and chimichurri.', category: 'proverb' },
  { id: 'p059', text: 'In Paraguay, sopa paraguaya is not a soup — and that is the joke that nourishes.', category: 'proverb' },
  { id: 'p060', text: 'A Costa Rican gallo pinto is breakfast that lasts until the next breakfast.', category: 'proverb' },
  { id: 'p061', text: 'In Panama, the sancocho is the cure for whatever the day brought.', category: 'proverb' },
  { id: 'p062', text: 'A Honduran baleada is folded, not stacked, and the cheese knows the difference.', category: 'proverb' },
  { id: 'p063', text: 'In Nicaragua, the gallo pinto is fried, and the conversation is louder for it.', category: 'proverb' },
  { id: 'p064', text: 'A Guatemalan pepián is darker than its mood — that is the chocolate.', category: 'proverb' },
  { id: 'p065', text: 'In Belize, the rice and beans are the foundation; everything else is decoration.', category: 'proverb' },
  { id: 'p066', text: 'A Trinidadian doubles is breakfast that knows what it is doing.', category: 'proverb' },
  { id: 'p067', text: 'In Barbados, the flying fish is fried before it remembers it was swimming.', category: 'proverb' },
  { id: 'p068', text: 'A Bahamian conch is tenderized by the cook who took their time.', category: 'proverb' },
  { id: 'p069', text: 'In Bermuda, the codfish breakfast was a Sunday before it was a recipe.', category: 'proverb' },
  { id: 'p070', text: 'A Hawaiian poke is dressed at the very last second, because the fish remembers the ocean.', category: 'proverb' },
];

const OBSERVATIONS: SazonQuip[] = [
  { id: 'o001', text: 'Saffron is worth its weight in gold — use a pinch and a smile.', category: 'observation' },
  { id: 'o002', text: 'Garlic is at its sweetest just before it browns. After that, it is a different ingredient.', category: 'observation' },
  { id: 'o003', text: 'Fresh thyme tastes like a garden; dried thyme tastes like a memory of one.', category: 'observation' },
  { id: 'o004', text: 'Onions caramelize for 45 minutes, no matter what the recipe says.', category: 'observation' },
  { id: 'o005', text: 'Olive oil that pours green is olive oil that means it.', category: 'observation' },
  { id: 'o006', text: 'A lemon zested is a lemon doubled.', category: 'observation' },
  { id: 'o007', text: 'Sea salt has texture; table salt has only saltiness.', category: 'observation' },
  { id: 'o008', text: 'Black pepper is a finishing spice as often as a starting one.', category: 'observation' },
  { id: 'o009', text: 'A whole spice toasted is a whole spice rediscovered.', category: 'observation' },
  { id: 'o010', text: 'Butter and olive oil together: butter is for flavor, oil is for the smoke point.', category: 'observation' },
  { id: 'o011', text: 'A roasted tomato concentrates the same way a stock does — slowly.', category: 'observation' },
  { id: 'o012', text: 'Anchovies dissolve into a sauce and leave only umami behind.', category: 'observation' },
  { id: 'o013', text: 'Capers brined are sharp; capers salted are bright.', category: 'observation' },
  { id: 'o014', text: 'A great mustard has both heat and history.', category: 'observation' },
  { id: 'o015', text: 'Rice rinsed three times is rice that knows what it owes you.', category: 'observation' },
  { id: 'o016', text: 'Onions in a hot pan need space; crowding makes them steam, not brown.', category: 'observation' },
  { id: 'o017', text: 'Fresh herbs go in at the end. Dried herbs go in at the beginning.', category: 'observation' },
  { id: 'o018', text: 'Acid wakes a dish up. A squeeze of lemon is the cheapest seasoning you own.', category: 'observation' },
  { id: 'o019', text: 'Browning is flavor; the brown bits at the bottom of the pan are dinner.', category: 'observation' },
  { id: 'o020', text: 'Pasta water is salty for a reason — pasta cooks in it, and so does the sauce.', category: 'observation' },
  { id: 'o021', text: 'A beef stew is best the next day. Always make twice as much.', category: 'observation' },
  { id: 'o022', text: 'Eggs are best at room temperature, no matter what the recipe says.', category: 'observation' },
  { id: 'o023', text: 'A whole chicken is cheaper than the parts and twice as forgiving.', category: 'observation' },
  { id: 'o024', text: 'Pumpkin seeds have more iron than spinach. Trust the snack.', category: 'observation' },
  { id: 'o025', text: 'Sumac is lemon you can store in a cupboard.', category: 'observation' },
  { id: 'o026', text: 'Za\'atar is a flavor and an entire mood.', category: 'observation' },
  { id: 'o027', text: 'Smoked paprika changes a dish without anyone noticing the smoke.', category: 'observation' },
  { id: 'o028', text: 'A bay leaf does not declare itself, but the dish notices when it is missing.', category: 'observation' },
  { id: 'o029', text: 'Coriander root is the best part of the plant. Most cooks throw it out.', category: 'observation' },
  { id: 'o030', text: 'Kombu and bonito make dashi; dashi makes everything else.', category: 'observation' },
  { id: 'o031', text: 'Miso is a finishing ingredient. Boiling it kills the friendly bacteria.', category: 'observation' },
  { id: 'o032', text: 'Tahini stirred too late will seize. Stir it warm, stir it slow.', category: 'observation' },
  { id: 'o033', text: 'A pomegranate gives up its seeds underwater. The kitchen stays clean.', category: 'observation' },
  { id: 'o034', text: 'Avocado oxidizes from the surface. Press the pit back in until you need it.', category: 'observation' },
  { id: 'o035', text: 'Brown butter is browned in 4 minutes and ruined in 5.', category: 'observation' },
  { id: 'o036', text: 'A rested steak is a juicier steak — the carryover is doing the work.', category: 'observation' },
  { id: 'o037', text: 'A boiled egg with a custardy yolk is six and a half minutes from cold tap water.', category: 'observation' },
  { id: 'o038', text: 'Beans soaked overnight cook in half the time and forgive twice as much.', category: 'observation' },
  { id: 'o039', text: 'Chickpeas roasted at 425°F are crunchy at minute 30 and burnt at minute 35.', category: 'observation' },
  { id: 'o040', text: 'Sweet potatoes baked whole stay sweeter than sweet potatoes peeled and cubed.', category: 'observation' },
  { id: 'o041', text: 'A cast iron seasoned for ten years is a cast iron worth willing to grandchildren.', category: 'observation' },
  { id: 'o042', text: 'A wooden spoon does not scratch a pan; it remembers what was cooked in it.', category: 'observation' },
  { id: 'o043', text: 'Mise en place is the difference between cooking and improvising.', category: 'observation' },
  { id: 'o044', text: 'Nuts toasted in a dry pan release oils that bottled oil cannot.', category: 'observation' },
  { id: 'o045', text: 'Sesame seeds toasted black are bitter; toasted golden are perfume.', category: 'observation' },
  { id: 'o046', text: 'Chili oil layered with Sichuan peppercorn is heat AND tingle — they are different.', category: 'observation' },
  { id: 'o047', text: 'Soy sauce light is for color; soy sauce dark is for depth.', category: 'observation' },
  { id: 'o048', text: 'Fish sauce smells alarming and tastes essential. Trust the gap.', category: 'observation' },
  { id: 'o049', text: 'A lime leaf is torn, never sliced — the oils are in the fold.', category: 'observation' },
  { id: 'o050', text: 'Galangal is not ginger. Substituting one for the other is a different dish.', category: 'observation' },
  { id: 'o051', text: 'Lemongrass is bruised before it goes in — that is where the flavor lives.', category: 'observation' },
  { id: 'o052', text: 'Cardamom green is for sweet; cardamom black is for savory. The cardboard kind is for nothing.', category: 'observation' },
  { id: 'o053', text: 'Cinnamon stick simmered is warmth; cinnamon ground stirred in is dessert.', category: 'observation' },
  { id: 'o054', text: 'Star anise has five points and is rarely used five at a time. One is plenty.', category: 'observation' },
  { id: 'o055', text: 'Cloves are the loudest spice in the cupboard. Use accordingly.', category: 'observation' },
  { id: 'o056', text: 'Fenugreek smells like maple syrup and tastes like nothing else.', category: 'observation' },
  { id: 'o057', text: 'Mustard seeds popped in oil are a different ingredient than mustard seeds whole.', category: 'observation' },
  { id: 'o058', text: 'Curry leaves are not garnish. Curry leaves are a layer.', category: 'observation' },
  { id: 'o059', text: 'A pinch of asafoetida replaces onions and garlic for anyone who needs it to.', category: 'observation' },
  { id: 'o060', text: 'Tarragon is bossy. A little goes a long way and a lot ruins lunch.', category: 'observation' },
  { id: 'o061', text: 'Dill belongs with cucumber, salmon, and yogurt — and quietly with eggs.', category: 'observation' },
  { id: 'o062', text: 'Chervil is the herb chefs miss when home cooks have not heard of it.', category: 'observation' },
  { id: 'o063', text: 'Lovage tastes like celery turned up to eleven.', category: 'observation' },
  { id: 'o064', text: 'A leek is an onion with a longer story.', category: 'observation' },
  { id: 'o065', text: 'A shallot caramelizes faster than an onion and apologizes later.', category: 'observation' },
  { id: 'o066', text: 'Spring onions are an ingredient, not a substitute for chives.', category: 'observation' },
  { id: 'o067', text: 'Garlic that sprouts is garlic that has had ideas. Use it anyway, just remove the green.', category: 'observation' },
  { id: 'o068', text: 'A roasted head of garlic is spread, not chopped.', category: 'observation' },
  { id: 'o069', text: 'A great chicken stock is built with feet — that is where the gelatin lives.', category: 'observation' },
  { id: 'o070', text: 'A slow-roast tomato has more flavor than a fast-roast tomato. Time is a seasoning.', category: 'observation' },
];

const PERSONALITY: SazonQuip[] = [
  { id: 'q001', text: 'Burnt garlic is just the kitchen telling you to slow down.', category: 'personality' },
  { id: 'q002', text: 'Reading the recipe twice is faster than fixing the dish once.', category: 'personality' },
  { id: 'q003', text: 'A clean cutting board is a calmer cook.', category: 'personality' },
  { id: 'q004', text: 'Taste as you go. The recipe was written for someone else\'s tongue.', category: 'personality' },
  { id: 'q005', text: 'Salt is a verb. Season at every step, not all at the end.', category: 'personality' },
  { id: 'q006', text: 'If a dish needs more, it usually needs acid before it needs salt.', category: 'personality' },
  { id: 'q007', text: 'A pan should be hot before the oil. The oil should shimmer before the food.', category: 'personality' },
  { id: 'q008', text: 'When in doubt, finish with butter.', category: 'personality' },
  { id: 'q009', text: 'When in doubt, finish with herbs.', category: 'personality' },
  { id: 'q010', text: 'When in doubt, finish with citrus.', category: 'personality' },
  { id: 'q011', text: 'Leftovers are tomorrow\'s lunch in disguise.', category: 'personality' },
  { id: 'q012', text: 'A pantry stocked with three kinds of vinegar is a pantry that solves problems.', category: 'personality' },
  { id: 'q013', text: 'Cook the food you actually want to eat. The fancy kind takes practice; the honest kind takes love.', category: 'personality' },
  { id: 'q014', text: 'A slow Sunday stew earns the rest of the week.', category: 'personality' },
  { id: 'q015', text: 'There is no such thing as too much fresh herb at the end of a meal.', category: 'personality' },
  { id: 'q016', text: 'If you forget to salt the pasta water, you will never forget again.', category: 'personality' },
  { id: 'q017', text: 'Crisp the rice. The crispy rice is the best rice.', category: 'personality' },
  { id: 'q018', text: 'Eat the world. Live well. Cook tonight.', category: 'personality' },
  { id: 'q019', text: 'A meal cooked is a small joy. A meal shared is a larger one.', category: 'personality' },
  { id: 'q020', text: 'The recipe is a map. The kitchen is the territory.', category: 'personality' },
  { id: 'q021', text: 'You only need three knives. The rest is decoration.', category: 'personality' },
  { id: 'q022', text: 'A sharp knife is a safe knife. A dull knife slips.', category: 'personality' },
  { id: 'q023', text: 'Wash as you go. Future-you is grateful.', category: 'personality' },
  { id: 'q024', text: 'A hot pan can wait. A cold pan cannot sear.', category: 'personality' },
  { id: 'q025', text: 'Salt the meat ahead of time. Always.', category: 'personality' },
  { id: 'q026', text: 'A grocery list written before hunger is a meal that goes well.', category: 'personality' },
  { id: 'q027', text: 'Cooking is not a performance. It is a practice.', category: 'personality' },
  { id: 'q028', text: 'A meal that takes 20 minutes can still be a meal you remember.', category: 'personality' },
  { id: 'q029', text: 'Frozen vegetables are not lesser vegetables. They were picked at peak.', category: 'personality' },
  { id: 'q030', text: 'A can of good tomatoes is a foundation. Buy the better can.', category: 'personality' },
  { id: 'q031', text: 'Spend on olive oil and salt. Save on everything else.', category: 'personality' },
  { id: 'q032', text: 'A great onion well browned can carry a whole dinner.', category: 'personality' },
  { id: 'q033', text: 'Bay leaf, peppercorn, parsley stems — your stock thanks you.', category: 'personality' },
  { id: 'q034', text: 'Cooking ahead is a kindness to your future self.', category: 'personality' },
  { id: 'q035', text: 'A beautiful plate starts with a wiped-clean rim.', category: 'personality' },
  { id: 'q036', text: 'Plate hot food on warm plates. Cold plates kill momentum.', category: 'personality' },
  { id: 'q037', text: 'Chiffonade is just a fancy word for slow ribbon-cuts. The hands learn it.', category: 'personality' },
  { id: 'q038', text: 'A great brunch is a rotation of four eggs you have already mastered.', category: 'personality' },
  { id: 'q039', text: 'A roast chicken is the entire personality test of a kitchen.', category: 'personality' },
  { id: 'q040', text: 'The best omelet is the one where you stopped caring how it looks.', category: 'personality' },
  { id: 'q041', text: 'A lazy Sunday makes a frittata a religion.', category: 'personality' },
  { id: 'q042', text: 'Toast is underrated. The bread, the butter, the time of day — all of it.', category: 'personality' },
  { id: 'q043', text: 'A homemade vinaigrette ruins store-bought dressing forever. You have been warned.', category: 'personality' },
  { id: 'q044', text: 'Dress the salad at the table. Wilted leaves are a tragedy.', category: 'personality' },
  { id: 'q045', text: 'Cook with both hands. The non-dominant hand learns faster than you think.', category: 'personality' },
  { id: 'q046', text: 'A fish needs less than you think. Salt, fat, heat, time.', category: 'personality' },
  { id: 'q047', text: 'Steaming is the most underrated cooking method in the Western kitchen.', category: 'personality' },
  { id: 'q048', text: 'A pressure cooker turns a Sunday stew into a Tuesday stew. Lifeline.', category: 'personality' },
  { id: 'q049', text: 'A dutch oven is a time machine to slow Sundays.', category: 'personality' },
  { id: 'q050', text: 'A sheet pan dinner is a kindness on a Wednesday.', category: 'personality' },
  { id: 'q051', text: 'Roast vegetables hotter than you think. 425°F is the floor, not the ceiling.', category: 'personality' },
  { id: 'q052', text: 'Salt the eggplant; press the eggplant; thank the eggplant.', category: 'personality' },
  { id: 'q053', text: 'A fennel bulb is a snack and a side and an entire mood.', category: 'personality' },
  { id: 'q054', text: 'Cabbage is the ingredient nobody talks about until it is the entire dinner.', category: 'personality' },
  { id: 'q055', text: 'A radish with butter and salt is a dinner in three ingredients.', category: 'personality' },
  { id: 'q056', text: 'A beet roasted whole tastes nothing like a beet boiled in pieces.', category: 'personality' },
  { id: 'q057', text: 'Carrot tops are pesto in waiting.', category: 'personality' },
  { id: 'q058', text: 'Beet greens are sauteed greens. Stop throwing them out.', category: 'personality' },
  { id: 'q059', text: 'Stale bread is a feature. Crouton, panzanella, ribollita.', category: 'personality' },
  { id: 'q060', text: 'Day-old rice is the only rice that fries properly. Plan for it.', category: 'personality' },
  { id: 'q061', text: 'Yogurt with garlic and salt is a sauce that goes with anything.', category: 'personality' },
  { id: 'q062', text: 'A jar of preserved lemons changes a kitchen forever.', category: 'personality' },
  { id: 'q063', text: 'Pickled red onions are a five-minute upgrade to anything.', category: 'personality' },
  { id: 'q064', text: 'A jammy egg makes a sad bowl beautiful.', category: 'personality' },
  { id: 'q065', text: 'Crispy chickpeas turn a salad into dinner.', category: 'personality' },
  { id: 'q066', text: 'A handful of toasted seeds rescues a bowl that needed crunch.', category: 'personality' },
  { id: 'q067', text: 'Furikake is the secret weapon of weeknight rice.', category: 'personality' },
  { id: 'q068', text: 'Chili crisp earns a permanent shelf in any pantry.', category: 'personality' },
  { id: 'q069', text: 'Hot honey on cheese is a peace treaty between sweet and savory.', category: 'personality' },
  { id: 'q070', text: 'A kitchen feels biggest when it is just you and one good knife.', category: 'personality' },
];

export const SAZON_QUIPS: SazonQuip[] = [
  ...PROVERBS,
  ...OBSERVATIONS,
  ...PERSONALITY,
];

const dayOfYear = (date: Date): number => {
  const start = Date.UTC(date.getUTCFullYear(), 0, 0);
  const current = Date.UTC(
    date.getUTCFullYear(),
    date.getUTCMonth(),
    date.getUTCDate(),
  );
  return Math.floor((current - start) / (1000 * 60 * 60 * 24));
};

export const pickQuipForDate = (date: Date): SazonQuip => {
  const doy = dayOfYear(date);
  const yearOffset = date.getUTCFullYear() % SAZON_QUIPS.length;
  const idx = (doy + yearOffset) % SAZON_QUIPS.length;
  return SAZON_QUIPS[idx];
};

export const getQuipById = (id: string): SazonQuip | null => {
  if (!id) return null;
  return SAZON_QUIPS.find((q) => q.id === id) ?? null;
};
