// Group 10R: Food Intel — curated tip library.
// Each tip declares personalizationKeys so the matcher can rank by user state
// (cuisine affinity, nutrient gap, skill tier, goal phase) rather than random rotation.

export type FoodIntelCategory =
  | 'superfood'
  | 'nutrient'
  | 'technique'
  | 'myth_bust'
  | 'pairing';

export type FoodIntelSkillTier = 'beginner' | 'cook' | 'chef';
export type FoodIntelGoalPhase = 'cut' | 'maintain' | 'bulk' | 'recomp' | 'any';

export interface FoodIntelPersonalizationKeys {
  cuisine: string[];
  nutrient: string[];
  skillTier: FoodIntelSkillTier[];
  goalPhase: FoodIntelGoalPhase[];
}

export interface FoodIntelTip {
  id: string;
  category: FoodIntelCategory;
  trigger: string;
  title: string;
  body: string;
  source?: string;
  tags: string[];
  personalizationKeys: FoodIntelPersonalizationKeys;
}

const ALL_TIERS: FoodIntelSkillTier[] = ['beginner', 'cook', 'chef'];
const ALL_PHASES: FoodIntelGoalPhase[] = ['cut', 'maintain', 'bulk', 'recomp', 'any'];

export const FOOD_INTEL_TIPS: FoodIntelTip[] = [
  // ─── Superfood usage (≥8) ───
  {
    id: 'sf-turmeric-pepper',
    category: 'superfood',
    trigger: 'turmeric',
    title: 'Pair turmeric with black pepper',
    body: 'Black pepper boosts curcumin absorption from turmeric by up to 2,000%. A pinch is enough.',
    tags: ['turmeric', 'black pepper', 'curcumin'],
    personalizationKeys: {
      cuisine: ['indian', 'thai', 'middle eastern'],
      nutrient: ['anti-inflammatory'],
      skillTier: ALL_TIERS,
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'sf-ginger-anti-inflam',
    category: 'superfood',
    trigger: 'ginger',
    title: 'Ginger calms inflammation',
    body: 'Fresh ginger contains gingerol — clinically shown to reduce muscle soreness and ease nausea.',
    tags: ['ginger', 'gingerol'],
    personalizationKeys: {
      cuisine: ['asian', 'chinese', 'thai', 'japanese'],
      nutrient: ['anti-inflammatory'],
      skillTier: ALL_TIERS,
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'sf-acv-blood-sugar',
    category: 'superfood',
    trigger: 'apple cider vinegar',
    title: 'ACV before carbs',
    body: 'A tablespoon of apple cider vinegar before a carb-heavy meal can blunt the blood sugar spike.',
    tags: ['apple cider vinegar', 'blood sugar'],
    personalizationKeys: {
      cuisine: [],
      nutrient: ['blood sugar'],
      skillTier: ALL_TIERS,
      goalPhase: ['cut', 'recomp'],
    },
  },
  {
    id: 'sf-fermented-gut',
    category: 'superfood',
    trigger: 'kimchi',
    title: 'Fermented foods feed your gut',
    body: 'Kimchi, sauerkraut, and miso deliver live probiotics. Cooking destroys them — add at the end.',
    tags: ['kimchi', 'sauerkraut', 'miso', 'fermented', 'probiotic'],
    personalizationKeys: {
      cuisine: ['korean', 'japanese', 'german'],
      nutrient: ['probiotic', 'gut health'],
      skillTier: ['cook', 'chef'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'sf-leafy-iron',
    category: 'superfood',
    trigger: 'spinach',
    title: 'Spinach iron + lemon',
    body: 'Plant iron in spinach absorbs 3× better with vitamin C. A squeeze of lemon does the trick.',
    tags: ['spinach', 'kale', 'iron', 'vitamin c'],
    personalizationKeys: {
      cuisine: ['mediterranean', 'middle eastern'],
      nutrient: ['iron'],
      skillTier: ALL_TIERS,
      goalPhase: ['cut', 'maintain', 'recomp'],
    },
  },
  {
    id: 'sf-chia-omega',
    category: 'superfood',
    trigger: 'chia seeds',
    title: 'Chia: tiny omega-3 powerhouse',
    body: 'A single tablespoon of chia gives you 2.5g of plant omega-3s and 4g of fiber. Soak first.',
    tags: ['chia', 'omega-3', 'fiber'],
    personalizationKeys: {
      cuisine: ['mexican', 'american'],
      nutrient: ['omega-3', 'fiber'],
      skillTier: ['beginner', 'cook'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'sf-cinnamon-glucose',
    category: 'superfood',
    trigger: 'cinnamon',
    title: 'Cinnamon dampens glucose response',
    body: 'A teaspoon of Ceylon cinnamon with carbs can reduce post-meal blood sugar by 10–20%.',
    tags: ['cinnamon', 'glucose', 'blood sugar'],
    personalizationKeys: {
      cuisine: ['middle eastern', 'mexican'],
      nutrient: ['blood sugar'],
      skillTier: ALL_TIERS,
      goalPhase: ['cut', 'recomp'],
    },
  },
  {
    id: 'sf-garlic-allicin',
    category: 'superfood',
    trigger: 'garlic',
    title: 'Crush garlic, then wait',
    body: 'Crushing garlic activates allicin — its main healthful compound. Let it sit 10 min before cooking.',
    tags: ['garlic', 'allicin'],
    personalizationKeys: {
      cuisine: ['italian', 'mediterranean', 'chinese', 'korean'],
      nutrient: ['anti-inflammatory'],
      skillTier: ['cook', 'chef'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'sf-matcha-l-theanine',
    category: 'superfood',
    trigger: 'matcha',
    title: 'Matcha: caffeine without the jitter',
    body: 'L-theanine in matcha smooths the caffeine curve. Same alertness, no crash.',
    tags: ['matcha', 'l-theanine', 'caffeine'],
    personalizationKeys: {
      cuisine: ['japanese'],
      nutrient: ['antioxidant'],
      skillTier: ALL_TIERS,
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'sf-hemp-complete',
    category: 'superfood',
    trigger: 'hemp seeds',
    title: 'Hemp: complete plant protein',
    body: 'Hemp seeds contain all 9 essential amino acids — rare for a plant. 10g protein per 3 tbsp.',
    tags: ['hemp seeds', 'protein', 'plant protein'],
    personalizationKeys: {
      cuisine: [],
      nutrient: ['protein'],
      skillTier: ['beginner', 'cook'],
      goalPhase: ['bulk', 'recomp'],
    },
  },

  // ─── Mineral & vitamin intel (≥8) ───
  {
    id: 'nu-magnesium-pumpkin',
    category: 'nutrient',
    trigger: 'pumpkin seeds',
    title: 'Pumpkin seeds = magnesium gold',
    body: 'A quarter cup gives 40% of your daily magnesium — supports sleep, muscle recovery, and mood.',
    tags: ['pumpkin seeds', 'magnesium'],
    personalizationKeys: {
      cuisine: ['mexican', 'middle eastern'],
      nutrient: ['magnesium'],
      skillTier: ALL_TIERS,
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'nu-iron-vitamin-c',
    category: 'nutrient',
    trigger: 'lentils',
    title: 'Plant iron needs vitamin C',
    body: 'Pair lentils, beans, or spinach with bell pepper, citrus, or tomato to triple iron absorption.',
    tags: ['lentils', 'beans', 'iron', 'vitamin c'],
    personalizationKeys: {
      cuisine: ['indian', 'mediterranean'],
      nutrient: ['iron'],
      skillTier: ALL_TIERS,
      goalPhase: ['cut', 'maintain', 'recomp'],
    },
  },
  {
    id: 'nu-zinc-shellfish',
    category: 'nutrient',
    trigger: 'oysters',
    title: 'Oysters crush zinc',
    body: 'Six oysters deliver 3× the daily zinc target — essential for immunity and testosterone.',
    tags: ['oysters', 'zinc'],
    personalizationKeys: {
      cuisine: ['french', 'japanese', 'american'],
      nutrient: ['zinc'],
      skillTier: ['cook', 'chef'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'nu-potassium-sweet-potato',
    category: 'nutrient',
    trigger: 'sweet potato',
    title: 'Beyond bananas for potassium',
    body: 'A sweet potato has 540mg potassium — more than a banana. White beans top them both.',
    tags: ['sweet potato', 'potassium'],
    personalizationKeys: {
      cuisine: ['american', 'caribbean'],
      nutrient: ['potassium'],
      skillTier: ALL_TIERS,
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'nu-b12-plant',
    category: 'nutrient',
    trigger: 'nutritional yeast',
    title: 'B12 for plant-based eaters',
    body: 'Nutritional yeast is one of the few non-animal B12 sources. Two tablespoons covers a full day.',
    tags: ['nutritional yeast', 'b12'],
    personalizationKeys: {
      cuisine: [],
      nutrient: ['b12'],
      skillTier: ['cook', 'chef'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'nu-vitamin-d-k2',
    category: 'nutrient',
    trigger: 'salmon',
    title: 'Vitamin D needs K2',
    body: 'Salmon delivers vitamin D, but K2 (egg yolks, hard cheese, natto) tells calcium where to go.',
    tags: ['salmon', 'vitamin d', 'vitamin k2'],
    personalizationKeys: {
      cuisine: ['japanese', 'mediterranean'],
      nutrient: ['vitamin d', 'vitamin k2'],
      skillTier: ['cook', 'chef'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'nu-selenium-brazil',
    category: 'nutrient',
    trigger: 'brazil nuts',
    title: 'Two Brazil nuts = full selenium',
    body: 'A single Brazil nut covers 100% of your daily selenium. Stop at two — more isn\'t better.',
    tags: ['brazil nuts', 'selenium'],
    personalizationKeys: {
      cuisine: [],
      nutrient: ['selenium'],
      skillTier: ALL_TIERS,
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'nu-omega-sardines',
    category: 'nutrient',
    trigger: 'sardines',
    title: 'Sardines: cheaper than salmon',
    body: 'Tinned sardines beat salmon on omega-3, calcium, and B12 — at a fraction of the cost.',
    tags: ['sardines', 'omega-3', 'calcium'],
    personalizationKeys: {
      cuisine: ['mediterranean', 'portuguese'],
      nutrient: ['omega-3', 'calcium'],
      skillTier: ['beginner', 'cook'],
      goalPhase: ['cut', 'maintain', 'recomp'],
    },
  },
  {
    id: 'nu-fiber-flax',
    category: 'nutrient',
    trigger: 'flax seeds',
    title: 'Grind flax to unlock it',
    body: 'Whole flax passes through undigested. Ground flax gives 3g fiber + 2g omega-3 per tablespoon.',
    tags: ['flax seeds', 'fiber', 'omega-3'],
    personalizationKeys: {
      cuisine: [],
      nutrient: ['fiber', 'omega-3'],
      skillTier: ALL_TIERS,
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'nu-calcium-tahini',
    category: 'nutrient',
    trigger: 'tahini',
    title: 'Tahini sneaks in calcium',
    body: 'Two tablespoons of tahini deliver 130mg calcium — without dairy. Drizzle on roasted veg.',
    tags: ['tahini', 'sesame', 'calcium'],
    personalizationKeys: {
      cuisine: ['middle eastern', 'mediterranean'],
      nutrient: ['calcium'],
      skillTier: ['cook', 'chef'],
      goalPhase: ALL_PHASES,
    },
  },

  // ─── Macro goal tips (≥8) ───
  {
    id: 'mg-protein-total',
    category: 'nutrient',
    trigger: 'chicken breast',
    title: 'Daily protein > meal timing',
    body: 'Hit your daily total — the 30-min "anabolic window" is mostly myth. Spread it across the day.',
    tags: ['chicken breast', 'protein', 'timing'],
    personalizationKeys: {
      cuisine: [],
      nutrient: ['protein'],
      skillTier: ALL_TIERS,
      goalPhase: ['bulk', 'recomp'],
    },
  },
  {
    id: 'mg-fiber-satiety',
    category: 'nutrient',
    trigger: 'oats',
    title: 'Fiber wins for fullness',
    body: 'Soluble fiber (oats, beans, apples) keeps you full longer than fat or simple carbs. Aim 25–35g daily.',
    tags: ['oats', 'fiber', 'satiety'],
    personalizationKeys: {
      cuisine: [],
      nutrient: ['fiber'],
      skillTier: ALL_TIERS,
      goalPhase: ['cut', 'recomp'],
    },
  },
  {
    id: 'mg-leucine-threshold',
    category: 'nutrient',
    trigger: 'whey protein',
    title: 'Hit the leucine threshold',
    body: 'Aim for 2.5g leucine per meal (~30g animal protein) to fully trigger muscle protein synthesis.',
    tags: ['whey protein', 'leucine', 'protein synthesis'],
    personalizationKeys: {
      cuisine: [],
      nutrient: ['protein', 'leucine'],
      skillTier: ['cook', 'chef'],
      goalPhase: ['bulk', 'recomp'],
    },
  },
  {
    id: 'mg-casein-night',
    category: 'nutrient',
    trigger: 'cottage cheese',
    title: 'Casein keeps muscle overnight',
    body: 'Cottage cheese or Greek yogurt before bed delivers slow-digesting casein for overnight repair.',
    tags: ['cottage cheese', 'greek yogurt', 'casein', 'protein'],
    personalizationKeys: {
      cuisine: [],
      nutrient: ['protein'],
      skillTier: ['beginner', 'cook'],
      goalPhase: ['bulk', 'recomp'],
    },
  },
  {
    id: 'mg-fat-not-fattening',
    category: 'myth_bust',
    trigger: 'olive oil',
    title: 'Fat doesn\'t make you fat',
    body: 'Excess calories do. A tablespoon of olive oil is 120 cal — adds satiety without spiking insulin.',
    tags: ['olive oil', 'fat', 'calories'],
    personalizationKeys: {
      cuisine: ['mediterranean', 'italian'],
      nutrient: ['fat'],
      skillTier: ALL_TIERS,
      goalPhase: ['cut', 'maintain', 'recomp'],
    },
  },
  {
    id: 'mg-30g-meal',
    category: 'nutrient',
    trigger: 'eggs',
    title: '30g protein per meal',
    body: 'Three eggs + Greek yogurt hits 30g — the per-meal benchmark for muscle synthesis at any age.',
    tags: ['eggs', 'protein'],
    personalizationKeys: {
      cuisine: [],
      nutrient: ['protein'],
      skillTier: ['beginner', 'cook'],
      goalPhase: ['bulk', 'recomp'],
    },
  },
  {
    id: 'mg-complete-doesnt-matter',
    category: 'myth_bust',
    trigger: 'rice and beans',
    title: 'You don\'t need complete proteins',
    body: 'The "combine plant proteins at every meal" rule is outdated. Variety across the day is enough.',
    tags: ['rice', 'beans', 'plant protein'],
    personalizationKeys: {
      cuisine: ['mexican', 'caribbean', 'indian'],
      nutrient: ['protein'],
      skillTier: ALL_TIERS,
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'mg-carb-timing',
    category: 'nutrient',
    trigger: 'rice',
    title: 'Save carbs for after training',
    body: 'Carbs near a workout shuttle into muscle, not fat stores. Useful for cuts, optional for maintenance.',
    tags: ['rice', 'carbs', 'timing'],
    personalizationKeys: {
      cuisine: ['asian'],
      nutrient: ['carbs'],
      skillTier: ['cook', 'chef'],
      goalPhase: ['cut', 'recomp'],
    },
  },

  // ─── Technique tips (≥8) ───
  {
    id: 'tc-soak-beans',
    category: 'technique',
    trigger: 'dried beans',
    title: 'Soak beans, dump the water',
    body: 'Soaking 8 hr leaches phytic acid and gas-causing oligosaccharides. Toss the soak liquid before cooking.',
    tags: ['dried beans', 'phytic acid'],
    personalizationKeys: {
      cuisine: ['mexican', 'middle eastern', 'indian'],
      nutrient: [],
      skillTier: ['cook', 'chef'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'tc-blanch-vs-boil',
    category: 'technique',
    trigger: 'broccoli',
    title: 'Blanch, don\'t boil',
    body: 'Boiling broccoli leaches 50% of its vitamin C into the water. Blanch 90 sec, then ice-bath.',
    tags: ['broccoli', 'blanching', 'vitamin c'],
    personalizationKeys: {
      cuisine: [],
      nutrient: ['vitamin c'],
      skillTier: ['cook', 'chef'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'tc-roast-garlic',
    category: 'technique',
    trigger: 'roasted garlic',
    title: 'Roast garlic for sweetness',
    body: 'Roasting mellows garlic\'s sharpness while keeping its allicin benefits. Spread it like butter.',
    tags: ['roasted garlic'],
    personalizationKeys: {
      cuisine: ['italian', 'mediterranean'],
      nutrient: [],
      skillTier: ['cook', 'chef'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'tc-sprout-grains',
    category: 'technique',
    trigger: 'sprouted',
    title: 'Sprouting unlocks nutrients',
    body: 'Sprouting grains and legumes activates enzymes, raises B-vitamins, and boosts protein bioavailability.',
    tags: ['sprouted', 'grains', 'legumes'],
    personalizationKeys: {
      cuisine: [],
      nutrient: ['protein'],
      skillTier: ['chef'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'tc-marinate-acid',
    category: 'technique',
    trigger: 'lime juice',
    title: 'Acid marinades have a clock',
    body: 'Citrus or vinegar marinades over 2 hrs turn protein mushy. Tougher cuts can go longer with yogurt.',
    tags: ['lime juice', 'lemon juice', 'vinegar', 'marinade'],
    personalizationKeys: {
      cuisine: ['mexican', 'mediterranean'],
      nutrient: [],
      skillTier: ['cook', 'chef'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'tc-cold-brew',
    category: 'technique',
    trigger: 'green tea',
    title: 'Cold-brew tea for smoother antioxidants',
    body: 'Cold-brewed green tea has more catechins and less bitterness. Steep 6 hr in the fridge.',
    tags: ['green tea', 'catechins'],
    personalizationKeys: {
      cuisine: ['japanese'],
      nutrient: ['antioxidant'],
      skillTier: ['beginner', 'cook'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'tc-rest-meat',
    category: 'technique',
    trigger: 'steak',
    title: 'Rest the meat half its cook time',
    body: 'A 6-min steak needs 3 min off-heat to redistribute juices. Cut early and the plate floods, not the bite.',
    tags: ['steak', 'beef', 'resting'],
    personalizationKeys: {
      cuisine: ['american', 'french'],
      nutrient: [],
      skillTier: ['cook', 'chef'],
      goalPhase: ['bulk', 'maintain'],
    },
  },
  {
    id: 'tc-toast-spices',
    category: 'technique',
    trigger: 'cumin',
    title: 'Bloom whole spices in fat',
    body: 'Toasting cumin, coriander, or mustard seeds in hot oil for 30 sec releases 10× more aroma.',
    tags: ['cumin', 'coriander', 'mustard seeds'],
    personalizationKeys: {
      cuisine: ['indian', 'middle eastern', 'mexican'],
      nutrient: [],
      skillTier: ['cook', 'chef'],
      goalPhase: ALL_PHASES,
    },
  },

  // ─── Myth busters (≥8) ───
  {
    id: 'mb-egg-yolks',
    category: 'myth_bust',
    trigger: 'eggs',
    title: 'Egg yolks aren\'t the enemy',
    body: 'The yolk holds the choline, vitamin D, B12, and most of the protein. Whole eggs raise HDL more than they raise LDL.',
    tags: ['eggs', 'cholesterol', 'choline'],
    personalizationKeys: {
      cuisine: [],
      nutrient: ['choline', 'vitamin d', 'b12'],
      skillTier: ALL_TIERS,
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'mb-celery-juice',
    category: 'myth_bust',
    trigger: 'celery juice',
    title: 'Celery juice isn\'t magic',
    body: 'It\'s just celery and water. Celery is genuinely healthy — but the morning ritual claims have no science behind them.',
    tags: ['celery juice', 'celery'],
    personalizationKeys: {
      cuisine: [],
      nutrient: [],
      skillTier: ALL_TIERS,
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'mb-detox-foods',
    category: 'myth_bust',
    trigger: 'detox tea',
    title: 'Your liver does the detoxing',
    body: 'No food "detoxes" you — your liver and kidneys do that 24/7. Cruciferous veg support liver enzymes, that\'s the real story.',
    tags: ['detox tea', 'detox'],
    personalizationKeys: {
      cuisine: [],
      nutrient: [],
      skillTier: ALL_TIERS,
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'mb-brown-vs-white',
    category: 'myth_bust',
    trigger: 'brown rice',
    title: 'Brown rice isn\'t always healthier',
    body: 'Brown rice has more fiber and minerals — but also more arsenic and phytic acid. Mix with white if you eat it daily.',
    tags: ['brown rice', 'white rice'],
    personalizationKeys: {
      cuisine: ['asian'],
      nutrient: ['fiber'],
      skillTier: ALL_TIERS,
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'mb-raw-tomato',
    category: 'myth_bust',
    trigger: 'tomatoes',
    title: 'Cooked tomatoes beat raw',
    body: 'Cooking tomatoes releases 3× more lycopene, the antioxidant linked to lower prostate cancer risk.',
    tags: ['tomatoes', 'lycopene'],
    personalizationKeys: {
      cuisine: ['italian', 'mediterranean'],
      nutrient: ['antioxidant'],
      skillTier: ['cook', 'chef'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'mb-microwave-nutrients',
    category: 'myth_bust',
    trigger: 'microwave',
    title: 'Microwaves don\'t kill nutrients',
    body: 'Microwaving preserves more vitamin C than boiling because cook time is shorter and less water is used.',
    tags: ['microwave'],
    personalizationKeys: {
      cuisine: [],
      nutrient: ['vitamin c'],
      skillTier: ['beginner'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'mb-organic-better',
    category: 'myth_bust',
    trigger: 'organic',
    title: 'Organic isn\'t always more nutritious',
    body: 'Organic produce has lower pesticide residue — but nutrient density depends more on freshness and soil than label.',
    tags: ['organic'],
    personalizationKeys: {
      cuisine: [],
      nutrient: [],
      skillTier: ALL_TIERS,
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'mb-sea-salt',
    category: 'myth_bust',
    trigger: 'sea salt',
    title: 'Sea salt = table salt, mostly',
    body: 'Both are 98% sodium chloride. Sea salt has trace minerals but no meaningful nutritional advantage.',
    tags: ['sea salt', 'table salt', 'sodium'],
    personalizationKeys: {
      cuisine: [],
      nutrient: ['sodium'],
      skillTier: ['beginner', 'cook'],
      goalPhase: ALL_PHASES,
    },
  },

  // ─── Pairing tips (≥8) ───
  {
    id: 'pr-tomato-olive-oil',
    category: 'pairing',
    trigger: 'olive oil',
    title: 'Olive oil unlocks tomato',
    body: 'Lycopene is fat-soluble — drizzle olive oil on cooked tomatoes for max absorption.',
    tags: ['olive oil', 'tomatoes', 'lycopene'],
    personalizationKeys: {
      cuisine: ['italian', 'mediterranean'],
      nutrient: ['antioxidant'],
      skillTier: ALL_TIERS,
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'pr-avocado-leafy',
    category: 'pairing',
    trigger: 'avocado',
    title: 'Avocado boosts greens',
    body: 'Adding half an avocado to a salad triples carotenoid absorption from leafy greens and carrots.',
    tags: ['avocado', 'salad', 'carotenoid'],
    personalizationKeys: {
      cuisine: ['mexican', 'american'],
      nutrient: ['vitamin a', 'antioxidant'],
      skillTier: ['beginner', 'cook'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'pr-greek-berries',
    category: 'pairing',
    trigger: 'greek yogurt',
    title: 'Greek yogurt + berries',
    body: 'Protein and slow carbs together blunt the sugar spike from fruit. 20g protein, 10g fiber in one bowl.',
    tags: ['greek yogurt', 'berries'],
    personalizationKeys: {
      cuisine: ['mediterranean'],
      nutrient: ['protein', 'fiber'],
      skillTier: ['beginner'],
      goalPhase: ['cut', 'maintain', 'recomp'],
    },
  },
  {
    id: 'pr-coffee-cinnamon',
    category: 'pairing',
    trigger: 'coffee',
    title: 'Cinnamon in coffee',
    body: 'A pinch of cinnamon in coffee dampens the cortisol spike and adds blood-sugar-friendly polyphenols.',
    tags: ['coffee', 'cinnamon'],
    personalizationKeys: {
      cuisine: [],
      nutrient: ['blood sugar'],
      skillTier: ['beginner', 'cook'],
      goalPhase: ['cut', 'recomp'],
    },
  },
  {
    id: 'pr-iron-no-tea',
    category: 'pairing',
    trigger: 'tea',
    title: 'Skip tea with iron-rich meals',
    body: 'Tannins in tea and coffee block iron absorption by up to 60%. Drink them an hour apart.',
    tags: ['tea', 'coffee', 'tannins', 'iron'],
    personalizationKeys: {
      cuisine: [],
      nutrient: ['iron'],
      skillTier: ['cook', 'chef'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'pr-broccoli-mustard',
    category: 'pairing',
    trigger: 'broccoli',
    title: 'Mustard wakes up broccoli',
    body: 'Adding mustard, horseradish, or arugula to cooked broccoli reactivates sulforaphane — its anti-cancer compound.',
    tags: ['broccoli', 'mustard', 'sulforaphane'],
    personalizationKeys: {
      cuisine: [],
      nutrient: ['antioxidant'],
      skillTier: ['cook', 'chef'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'pr-banana-pb',
    category: 'pairing',
    trigger: 'banana',
    title: 'Banana + peanut butter',
    body: 'Carbs from the banana shuttle the protein and fat from the PB into recovery faster post-workout.',
    tags: ['banana', 'peanut butter'],
    personalizationKeys: {
      cuisine: [],
      nutrient: ['protein', 'carbs'],
      skillTier: ['beginner'],
      goalPhase: ['bulk', 'recomp'],
    },
  },
  {
    id: 'pr-rice-beans',
    category: 'pairing',
    trigger: 'beans',
    title: 'Rice and beans = full amino set',
    body: 'Rice is low in lysine; beans are low in methionine. Together they cover every essential amino acid.',
    tags: ['rice', 'beans', 'lysine', 'methionine'],
    personalizationKeys: {
      cuisine: ['mexican', 'caribbean', 'cajun'],
      nutrient: ['protein'],
      skillTier: ['beginner', 'cook'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'pr-citrus-greens',
    category: 'pairing',
    trigger: 'kale',
    title: 'Citrus on greens for iron',
    body: 'Squeeze lemon over kale, spinach, or chard — vitamin C makes plant iron 3× more absorbable.',
    tags: ['kale', 'spinach', 'lemon', 'iron'],
    personalizationKeys: {
      cuisine: ['mediterranean'],
      nutrient: ['iron'],
      skillTier: ['beginner', 'cook'],
      goalPhase: ['cut', 'maintain', 'recomp'],
    },
  },

  // ─── Additional fillers across categories to comfortably exceed 80 ───
  {
    id: 'sf-blueberries-brain',
    category: 'superfood',
    trigger: 'blueberries',
    title: 'Blueberries protect your brain',
    body: 'Anthocyanins in blueberries cross the blood-brain barrier and improve memory. A cup a day is the studied dose.',
    tags: ['blueberries', 'anthocyanins'],
    personalizationKeys: {
      cuisine: ['american'],
      nutrient: ['antioxidant'],
      skillTier: ALL_TIERS,
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'sf-mushrooms-d',
    category: 'superfood',
    trigger: 'mushrooms',
    title: 'Sun-bathe your mushrooms',
    body: 'Mushrooms left in sunlight gill-side-up for 30 min generate vitamin D — one of the few plant sources.',
    tags: ['mushrooms', 'vitamin d'],
    personalizationKeys: {
      cuisine: ['asian'],
      nutrient: ['vitamin d'],
      skillTier: ['chef'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'sf-cacao-flavanol',
    category: 'superfood',
    trigger: 'dark chocolate',
    title: 'Dark chocolate, real benefit',
    body: 'Cocoa flavanols (≥70% cacao) improve blood flow and lower BP. 1oz square daily is the cardiology dose.',
    tags: ['dark chocolate', 'cacao'],
    personalizationKeys: {
      cuisine: [],
      nutrient: ['antioxidant', 'magnesium'],
      skillTier: ALL_TIERS,
      goalPhase: ['maintain', 'recomp'],
    },
  },
  {
    id: 'nu-iodine-seaweed',
    category: 'nutrient',
    trigger: 'seaweed',
    title: 'Seaweed: iodine in one bite',
    body: 'A single nori sheet covers a full day\'s iodine — critical for thyroid hormone production.',
    tags: ['seaweed', 'nori', 'iodine'],
    personalizationKeys: {
      cuisine: ['japanese', 'korean'],
      nutrient: ['iodine'],
      skillTier: ['cook', 'chef'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'nu-choline-egg',
    category: 'nutrient',
    trigger: 'eggs',
    title: 'Eggs are a choline staple',
    body: 'Two eggs cover half your daily choline target — vital for brain, liver, and pregnancy health.',
    tags: ['eggs', 'choline'],
    personalizationKeys: {
      cuisine: [],
      nutrient: ['choline'],
      skillTier: ['beginner', 'cook'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'tc-salt-pasta-water',
    category: 'technique',
    trigger: 'pasta',
    title: 'Salt pasta water like the sea',
    body: 'A heaping tablespoon per quart. It\'s your only chance to season pasta from inside the noodle.',
    tags: ['pasta'],
    personalizationKeys: {
      cuisine: ['italian'],
      nutrient: [],
      skillTier: ['cook', 'chef'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'tc-pat-dry-protein',
    category: 'technique',
    trigger: 'chicken thigh',
    title: 'Dry the protein for crispy skin',
    body: 'Pat chicken or fish dry with paper towels before searing. Wet protein steams instead of browning.',
    tags: ['chicken thigh', 'fish'],
    personalizationKeys: {
      cuisine: [],
      nutrient: [],
      skillTier: ['cook', 'chef'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'pr-honey-cinnamon',
    category: 'pairing',
    trigger: 'honey',
    title: 'Honey + cinnamon for inflammation',
    body: 'Both are anti-inflammatory; together they\'re studied for arthritis and oxidative stress relief.',
    tags: ['honey', 'cinnamon'],
    personalizationKeys: {
      cuisine: ['middle eastern'],
      nutrient: ['anti-inflammatory'],
      skillTier: ['beginner'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'mb-fruit-sugar',
    category: 'myth_bust',
    trigger: 'fruit',
    title: 'Whole fruit isn\'t the enemy',
    body: 'Fiber in whole fruit slows sugar absorption. The villain is fruit juice — same sugar, no fiber.',
    tags: ['fruit', 'fruit juice'],
    personalizationKeys: {
      cuisine: [],
      nutrient: ['fiber', 'sugar'],
      skillTier: ALL_TIERS,
      goalPhase: ['cut', 'maintain', 'recomp'],
    },
  },
  {
    id: 'sf-walnut-omega',
    category: 'superfood',
    trigger: 'walnuts',
    title: 'Walnuts: plant omega-3s',
    body: 'A quarter cup of walnuts gives you a full day of plant ALA omega-3 — heart and brain support.',
    tags: ['walnuts', 'omega-3'],
    personalizationKeys: {
      cuisine: ['mediterranean', 'middle eastern'],
      nutrient: ['omega-3'],
      skillTier: ALL_TIERS,
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'sf-kefir-probiotic',
    category: 'superfood',
    trigger: 'kefir',
    title: 'Kefir packs more strains than yogurt',
    body: 'Kefir delivers 30+ probiotic strains versus yogurt\'s handful — broader gut microbiome support.',
    tags: ['kefir', 'probiotic'],
    personalizationKeys: {
      cuisine: ['middle eastern', 'eastern european'],
      nutrient: ['probiotic', 'gut health'],
      skillTier: ['cook', 'chef'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'sf-miso-umami',
    category: 'superfood',
    trigger: 'miso',
    title: 'Don\'t boil miso',
    body: 'High heat kills miso\'s probiotics. Stir it in off-heat for live bacteria + savory umami.',
    tags: ['miso', 'umami', 'probiotic'],
    personalizationKeys: {
      cuisine: ['japanese'],
      nutrient: ['probiotic'],
      skillTier: ['cook', 'chef'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'nu-vitamin-c-pepper',
    category: 'nutrient',
    trigger: 'bell pepper',
    title: 'Bell pepper out-Cs the orange',
    body: 'A red bell pepper has 3× more vitamin C than an orange. Eat raw — heat degrades it fast.',
    tags: ['bell pepper', 'vitamin c'],
    personalizationKeys: {
      cuisine: ['mexican', 'mediterranean'],
      nutrient: ['vitamin c'],
      skillTier: ['beginner', 'cook'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'nu-folate-asparagus',
    category: 'nutrient',
    trigger: 'asparagus',
    title: 'Asparagus is folate-dense',
    body: 'Half a cup of asparagus delivers 35% of daily folate — critical for cell division and pregnancy.',
    tags: ['asparagus', 'folate'],
    personalizationKeys: {
      cuisine: ['italian', 'french'],
      nutrient: ['folate'],
      skillTier: ['cook', 'chef'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'nu-collagen-bone-broth',
    category: 'nutrient',
    trigger: 'bone broth',
    title: 'Bone broth for joint collagen',
    body: 'Long-simmered bone broth pulls out glycine and proline — building blocks of collagen and joint health.',
    tags: ['bone broth', 'collagen', 'glycine'],
    personalizationKeys: {
      cuisine: ['american', 'french', 'asian'],
      nutrient: ['protein', 'collagen'],
      skillTier: ['chef'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'mg-protein-spread',
    category: 'nutrient',
    trigger: 'tuna',
    title: 'Spread protein across meals',
    body: '4 meals at 30g protein out-builds muscle vs. 2 meals at 60g. Frequent leucine pulses win.',
    tags: ['tuna', 'protein'],
    personalizationKeys: {
      cuisine: [],
      nutrient: ['protein'],
      skillTier: ['cook', 'chef'],
      goalPhase: ['bulk', 'recomp'],
    },
  },
  {
    id: 'mg-volume-eating',
    category: 'nutrient',
    trigger: 'cucumber',
    title: 'Volume eating beats hunger',
    body: 'Low-cal high-volume foods (cucumber, lettuce, berries, popcorn) fill the stomach without the calories.',
    tags: ['cucumber', 'lettuce', 'volume'],
    personalizationKeys: {
      cuisine: [],
      nutrient: ['fiber'],
      skillTier: ['beginner'],
      goalPhase: ['cut'],
    },
  },
  {
    id: 'tc-knife-stable',
    category: 'technique',
    trigger: 'onion',
    title: 'Cut a flat side first',
    body: 'Round vegetables roll. Slice off a flat side and rest it down before cutting — saves fingers.',
    tags: ['onion', 'tomato', 'knife skills'],
    personalizationKeys: {
      cuisine: [],
      nutrient: [],
      skillTier: ['beginner'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'tc-deglaze-pan',
    category: 'technique',
    trigger: 'wine',
    title: 'Deglaze for instant sauce',
    body: 'Wine, broth, or vinegar splashed into a hot pan lifts browned bits (fond) into a savory sauce.',
    tags: ['wine', 'broth', 'deglaze'],
    personalizationKeys: {
      cuisine: ['french', 'italian'],
      nutrient: [],
      skillTier: ['cook', 'chef'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'tc-mise-en-place',
    category: 'technique',
    trigger: 'mise en place',
    title: 'Prep before you heat the pan',
    body: 'Chop, measure, and gather everything before cooking. Stir-fries and sears wait for nothing.',
    tags: ['mise en place', 'prep'],
    personalizationKeys: {
      cuisine: ['french', 'asian'],
      nutrient: [],
      skillTier: ['beginner', 'cook'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'tc-finish-with-acid',
    category: 'technique',
    trigger: 'lemon',
    title: 'Finish with acid',
    body: 'A squeeze of lemon or splash of vinegar at the end brightens any dish that tastes "flat."',
    tags: ['lemon', 'vinegar', 'finishing'],
    personalizationKeys: {
      cuisine: ['mediterranean'],
      nutrient: [],
      skillTier: ['cook', 'chef'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'pr-tomato-basil',
    category: 'pairing',
    trigger: 'basil',
    title: 'Tomato + basil + olive oil',
    body: 'Basil\'s vitamin K and tomato\'s lycopene — both fat-soluble. Olive oil triples absorption.',
    tags: ['basil', 'tomatoes', 'olive oil'],
    personalizationKeys: {
      cuisine: ['italian'],
      nutrient: ['vitamin k', 'antioxidant'],
      skillTier: ['beginner', 'cook'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'pr-yogurt-honey',
    category: 'pairing',
    trigger: 'honey',
    title: 'Yogurt + honey beats sugar bowls',
    body: 'Honey\'s antioxidants survive when added to yogurt cold. Stir in last to keep the live cultures intact.',
    tags: ['yogurt', 'honey'],
    personalizationKeys: {
      cuisine: ['mediterranean', 'middle eastern'],
      nutrient: ['probiotic', 'antioxidant'],
      skillTier: ['beginner'],
      goalPhase: ['maintain', 'recomp'],
    },
  },
  {
    id: 'pr-broccoli-garlic',
    category: 'pairing',
    trigger: 'garlic',
    title: 'Garlic with cruciferous veg',
    body: 'Garlic\'s sulfur compounds amplify the cancer-fighting glucosinolates in broccoli, kale, and cauliflower.',
    tags: ['garlic', 'broccoli', 'kale'],
    personalizationKeys: {
      cuisine: ['italian', 'asian'],
      nutrient: ['antioxidant'],
      skillTier: ['cook', 'chef'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'mb-msg-safe',
    category: 'myth_bust',
    trigger: 'msg',
    title: 'MSG is safe',
    body: 'The "Chinese restaurant syndrome" panic was debunked decades ago. MSG is umami, not poison.',
    tags: ['msg', 'umami'],
    personalizationKeys: {
      cuisine: ['chinese', 'japanese', 'korean', 'thai'],
      nutrient: [],
      skillTier: ['cook', 'chef'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'mb-frozen-fresh',
    category: 'myth_bust',
    trigger: 'frozen vegetables',
    title: 'Frozen veg often beats "fresh"',
    body: 'Frozen at peak ripeness, frozen vegetables can hold more nutrients than "fresh" produce that traveled a week.',
    tags: ['frozen vegetables', 'frozen'],
    personalizationKeys: {
      cuisine: [],
      nutrient: ['vitamin c'],
      skillTier: ['beginner'],
      goalPhase: ALL_PHASES,
    },
  },
  {
    id: 'tc-low-and-slow',
    category: 'technique',
    trigger: 'pork shoulder',
    title: 'Low and slow breaks down collagen',
    body: 'Tough cuts (shoulder, brisket) need 6+ hours below 200°F to convert collagen into silky gelatin.',
    tags: ['pork shoulder', 'brisket', 'collagen'],
    personalizationKeys: {
      cuisine: ['american', 'mexican'],
      nutrient: ['collagen'],
      skillTier: ['chef'],
      goalPhase: ALL_PHASES,
    },
  },
];
